// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExternalEvents = `-- name: CountExternalEvents :one
SELECT COUNT(*)::bigint AS count
FROM external_events e
JOIN event_sources es ON es.id = e.source_id AND es.is_active = true
LEFT JOIN cities c ON c.id = e.city_id AND c.is_active = true
WHERE ($1::text IS NULL OR c.slug = $1)
`

func (q *Queries) CountExternalEvents(ctx context.Context, citySlug *string) (int64, error) {
	row := q.db.QueryRow(ctx, countExternalEvents, citySlug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listExternalEvents = `-- name: ListExternalEvents :many
SELECT
  e.id::text AS id,
  e.event_name,
  e.event_url,
  e.venue_name,
  e.venue_url,
  e.schedule_text,
  e.music_text,
  e.description,
  e.poster_image_url,
  e.imported_at,
  c.slug AS city_slug,
  c.name AS city_name,
  es.slug AS source_slug,
  es.name AS source_name
FROM external_events e
JOIN event_sources es ON es.id = e.source_id AND es.is_active = true
LEFT JOIN cities c ON c.id = e.city_id AND c.is_active = true
WHERE ($1::text IS NULL OR c.slug = $1)
ORDER BY e.imported_at DESC, e.event_name ASC
LIMIT $3::int
OFFSET $2::int
`

type ListExternalEventsParams struct {
	CitySlug  *string `json:"city_slug"`
	OffsetVal int32   `json:"offset_val"`
	LimitVal  int32   `json:"limit_val"`
}

type ListExternalEventsRow struct {
	ID             string             `json:"id"`
	EventName      string             `json:"event_name"`
	EventUrl       string             `json:"event_url"`
	VenueName      *string            `json:"venue_name"`
	VenueUrl       *string            `json:"venue_url"`
	ScheduleText   *string            `json:"schedule_text"`
	MusicText      *string            `json:"music_text"`
	Description    *string            `json:"description"`
	PosterImageUrl *string            `json:"poster_image_url"`
	ImportedAt     pgtype.Timestamptz `json:"imported_at"`
	CitySlug       *string            `json:"city_slug"`
	CityName       *string            `json:"city_name"`
	SourceSlug     string             `json:"source_slug"`
	SourceName     string             `json:"source_name"`
}

func (q *Queries) ListExternalEvents(ctx context.Context, arg ListExternalEventsParams) ([]ListExternalEventsRow, error) {
	rows, err := q.db.Query(ctx, listExternalEvents, arg.CitySlug, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExternalEventsRow
	for rows.Next() {
		var i ListExternalEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventName,
			&i.EventUrl,
			&i.VenueName,
			&i.VenueUrl,
			&i.ScheduleText,
			&i.MusicText,
			&i.Description,
			&i.PosterImageUrl,
			&i.ImportedAt,
			&i.CitySlug,
			&i.CityName,
			&i.SourceSlug,
			&i.SourceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingEvents = `-- name: ListUpcomingEvents :many
SELECT
  e.id::text AS id,
  e.event_name,
  e.event_url,
  e.venue_name,
  e.venue_url,
  e.schedule_text,
  e.music_text,
  e.description,
  e.poster_image_url,
  e.imported_at,
  c.slug AS city_slug,
  c.name AS city_name,
  es.slug AS source_slug,
  es.name AS source_name
FROM external_events e
JOIN event_sources es ON es.id = e.source_id AND es.is_active = true
LEFT JOIN cities c ON c.id = e.city_id AND c.is_active = true
WHERE e.poster_image_url IS NOT NULL
  AND ($1::text IS NULL OR c.slug = $1)
ORDER BY e.imported_at DESC, e.event_name ASC
LIMIT $2::int
`

type ListUpcomingEventsParams struct {
	CitySlug *string `json:"city_slug"`
	LimitVal int32   `json:"limit_val"`
}

type ListUpcomingEventsRow struct {
	ID             string             `json:"id"`
	EventName      string             `json:"event_name"`
	EventUrl       string             `json:"event_url"`
	VenueName      *string            `json:"venue_name"`
	VenueUrl       *string            `json:"venue_url"`
	ScheduleText   *string            `json:"schedule_text"`
	MusicText      *string            `json:"music_text"`
	Description    *string            `json:"description"`
	PosterImageUrl *string            `json:"poster_image_url"`
	ImportedAt     pgtype.Timestamptz `json:"imported_at"`
	CitySlug       *string            `json:"city_slug"`
	CityName       *string            `json:"city_name"`
	SourceSlug     string             `json:"source_slug"`
	SourceName     string             `json:"source_name"`
}

func (q *Queries) ListUpcomingEvents(ctx context.Context, arg ListUpcomingEventsParams) ([]ListUpcomingEventsRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingEvents, arg.CitySlug, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpcomingEventsRow
	for rows.Next() {
		var i ListUpcomingEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventName,
			&i.EventUrl,
			&i.VenueName,
			&i.VenueUrl,
			&i.ScheduleText,
			&i.MusicText,
			&i.Description,
			&i.PosterImageUrl,
			&i.ImportedAt,
			&i.CitySlug,
			&i.CityName,
			&i.SourceSlug,
			&i.SourceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
