// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lists.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createListSyncRun = `-- name: CreateListSyncRun :one
INSERT INTO list_sync_runs (status)
VALUES ('running')
RETURNING id::text AS id
`

func (q *Queries) CreateListSyncRun(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, createListSyncRun)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO place_lists (
  slug,
  title,
  subtitle,
  category,
  area,
  occasions,
  city_id,
  creator_user_id,
  list_type,
  visibility,
  saves_count,
  sort_order,
  is_active
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7::uuid,
  $8::uuid,
  'user_plan',
  $9,
  $10::integer,
  $11::integer,
  true
)
RETURNING id::text AS id
`

type CreatePlanParams struct {
	Slug          string      `json:"slug"`
	Title         string      `json:"title"`
	Subtitle      string      `json:"subtitle"`
	Category      string      `json:"category"`
	Area          string      `json:"area"`
	Occasions     []string    `json:"occasions"`
	CityID        pgtype.UUID `json:"city_id"`
	CreatorUserID pgtype.UUID `json:"creator_user_id"`
	Visibility    string      `json:"visibility"`
	SavesCount    int32       `json:"saves_count"`
	SortOrder     int32       `json:"sort_order"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (string, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.Slug,
		arg.Title,
		arg.Subtitle,
		arg.Category,
		arg.Area,
		arg.Occasions,
		arg.CityID,
		arg.CreatorUserID,
		arg.Visibility,
		arg.SavesCount,
		arg.SortOrder,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createPlanEntry = `-- name: CreatePlanEntry :exec
INSERT INTO place_list_entries (
  list_id,
  place_id,
  seed_name,
  rank,
  note,
  time_label,
  activity_type,
  image_url,
  is_active
)
VALUES (
  $1::uuid,
  $2::uuid,
  $3,
  $4::integer,
  $5,
  $6,
  $7,
  $8,
  true
)
`

type CreatePlanEntryParams struct {
	ListID       pgtype.UUID `json:"list_id"`
	PlaceID      pgtype.UUID `json:"place_id"`
	SeedName     string      `json:"seed_name"`
	Rank         int32       `json:"rank"`
	Note         string      `json:"note"`
	TimeLabel    string      `json:"time_label"`
	ActivityType string      `json:"activity_type"`
	ImageUrl     *string     `json:"image_url"`
}

func (q *Queries) CreatePlanEntry(ctx context.Context, arg CreatePlanEntryParams) error {
	_, err := q.db.Exec(ctx, createPlanEntry,
		arg.ListID,
		arg.PlaceID,
		arg.SeedName,
		arg.Rank,
		arg.Note,
		arg.TimeLabel,
		arg.ActivityType,
		arg.ImageUrl,
	)
	return err
}

const createPlanPlace = `-- name: CreatePlanPlace :one
INSERT INTO places (
  city_id,
  google_place_id,
  source,
  name,
  neighborhood,
  address,
  latitude,
  longitude,
  cover_image_url,
  tags,
  is_active
)
VALUES (
  $1::uuid,
  $2,
  CASE WHEN $2::text IS NULL THEN 'curated' ELSE 'google' END,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  true
)
ON CONFLICT (google_place_id) DO UPDATE
SET
  name = EXCLUDED.name,
  neighborhood = COALESCE(EXCLUDED.neighborhood, places.neighborhood),
  address = COALESCE(EXCLUDED.address, places.address),
  latitude = COALESCE(EXCLUDED.latitude, places.latitude),
  longitude = COALESCE(EXCLUDED.longitude, places.longitude),
  cover_image_url = COALESCE(EXCLUDED.cover_image_url, places.cover_image_url),
  tags = CASE
    WHEN cardinality(EXCLUDED.tags) > 0 THEN EXCLUDED.tags
    ELSE places.tags
  END,
  updated_at = now()
RETURNING id::text AS id
`

type CreatePlanPlaceParams struct {
	CityID        pgtype.UUID    `json:"city_id"`
	GooglePlaceID *string        `json:"google_place_id"`
	Name          string         `json:"name"`
	Neighborhood  *string        `json:"neighborhood"`
	Address       *string        `json:"address"`
	Latitude      pgtype.Numeric `json:"latitude"`
	Longitude     pgtype.Numeric `json:"longitude"`
	CoverImageUrl *string        `json:"cover_image_url"`
	Tags          []string       `json:"tags"`
}

func (q *Queries) CreatePlanPlace(ctx context.Context, arg CreatePlanPlaceParams) (string, error) {
	row := q.db.QueryRow(ctx, createPlanPlace,
		arg.CityID,
		arg.GooglePlaceID,
		arg.Name,
		arg.Neighborhood,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.CoverImageUrl,
		arg.Tags,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deactivatePlaceListEntriesNotInSeedNames = `-- name: DeactivatePlaceListEntriesNotInSeedNames :execrows
UPDATE place_list_entries
SET
  is_active = false,
  updated_at = now()
WHERE list_id = $1::uuid
  AND is_active = true
  AND NOT (seed_name = ANY($2::text[]))
`

type DeactivatePlaceListEntriesNotInSeedNamesParams struct {
	ListID    pgtype.UUID `json:"list_id"`
	SeedNames []string    `json:"seed_names"`
}

func (q *Queries) DeactivatePlaceListEntriesNotInSeedNames(ctx context.Context, arg DeactivatePlaceListEntriesNotInSeedNamesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivatePlaceListEntriesNotInSeedNames, arg.ListID, arg.SeedNames)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findPlaceByNameInCity = `-- name: FindPlaceByNameInCity :one
SELECT id::text AS id
FROM places
WHERE city_id = $1::uuid
  AND is_active = true
  AND lower(trim(name)) = lower(trim($2))
LIMIT 1
`

type FindPlaceByNameInCityParams struct {
	CityID pgtype.UUID `json:"city_id"`
	Name   string      `json:"name"`
}

func (q *Queries) FindPlaceByNameInCity(ctx context.Context, arg FindPlaceByNameInCityParams) (string, error) {
	row := q.db.QueryRow(ctx, findPlaceByNameInCity, arg.CityID, arg.Name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const finishListSyncRun = `-- name: FinishListSyncRun :exec
UPDATE list_sync_runs
SET
  finished_at = now(),
  status = $1,
  entries_added = $2::integer,
  entries_skipped = $3::integer,
  entries_failed = $4::integer,
  details = $5
WHERE id = $6::uuid
`

type FinishListSyncRunParams struct {
	Status         string      `json:"status"`
	EntriesAdded   int32       `json:"entries_added"`
	EntriesSkipped int32       `json:"entries_skipped"`
	EntriesFailed  int32       `json:"entries_failed"`
	Details        []byte      `json:"details"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) FinishListSyncRun(ctx context.Context, arg FinishListSyncRunParams) error {
	_, err := q.db.Exec(ctx, finishListSyncRun,
		arg.Status,
		arg.EntriesAdded,
		arg.EntriesSkipped,
		arg.EntriesFailed,
		arg.Details,
		arg.ID,
	)
	return err
}

const getCityByHint = `-- name: GetCityByHint :one
SELECT
  id::text AS id,
  slug,
  name,
  latitude,
  longitude
FROM cities
WHERE is_active = true
  AND (
    lower(name) = lower($1)
    OR lower(slug) = lower($1)
    OR lower(name) = lower($2)
    OR lower(slug) = lower($2)
  )
ORDER BY sort_order
LIMIT 1
`

type GetCityByHintParams struct {
	CityHint    string `json:"city_hint"`
	CityHintAlt string `json:"city_hint_alt"`
}

type GetCityByHintRow struct {
	ID        string         `json:"id"`
	Slug      string         `json:"slug"`
	Name      string         `json:"name"`
	Latitude  pgtype.Numeric `json:"latitude"`
	Longitude pgtype.Numeric `json:"longitude"`
}

func (q *Queries) GetCityByHint(ctx context.Context, arg GetCityByHintParams) (GetCityByHintRow, error) {
	row := q.db.QueryRow(ctx, getCityByHint, arg.CityHint, arg.CityHintAlt)
	var i GetCityByHintRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getPlaceListByID = `-- name: GetPlaceListByID :one
SELECT
  pl.id::text AS id,
  pl.slug,
  pl.title,
  pl.subtitle,
  pl.category,
  pl.area,
  pl.occasions,
  pl.sort_order,
  pl.source_hash,
  pl.list_type,
  pl.visibility,
  pl.saves_count,
  pl.city_id::text AS city_id,
  c.slug AS city_slug,
  c.name AS city_name,
  COALESCE(pl.creator_user_id::text, ''::text)::text AS creator_user_id,
  COALESCE(NULLIF(trim(concat_ws(' ', up.first_name, up.last_name)), ''), up.username::text, u.primary_email) AS creator_display_name,
  COALESCE(up.username::text, ''::text)::text AS creator_username,
  up.avatar_url AS creator_avatar_url,
  (
    SELECT COUNT(*)::integer
    FROM place_list_entries ple
    WHERE ple.list_id = pl.id
      AND ple.is_active = true
  ) AS stops_count
FROM place_lists pl
JOIN cities c ON c.id = pl.city_id
LEFT JOIN users u ON u.id = pl.creator_user_id
LEFT JOIN user_profiles up ON up.user_id = pl.creator_user_id
WHERE pl.id = $1::uuid
`

type GetPlaceListByIDRow struct {
	ID                 string   `json:"id"`
	Slug               string   `json:"slug"`
	Title              string   `json:"title"`
	Subtitle           string   `json:"subtitle"`
	Category           string   `json:"category"`
	Area               string   `json:"area"`
	Occasions          []string `json:"occasions"`
	SortOrder          int32    `json:"sort_order"`
	SourceHash         *string  `json:"source_hash"`
	ListType           string   `json:"list_type"`
	Visibility         string   `json:"visibility"`
	SavesCount         int32    `json:"saves_count"`
	CityID             string   `json:"city_id"`
	CitySlug           string   `json:"city_slug"`
	CityName           string   `json:"city_name"`
	CreatorUserID      string   `json:"creator_user_id"`
	CreatorDisplayName *string  `json:"creator_display_name"`
	CreatorUsername    string   `json:"creator_username"`
	CreatorAvatarUrl   *string  `json:"creator_avatar_url"`
	StopsCount         int32    `json:"stops_count"`
}

func (q *Queries) GetPlaceListByID(ctx context.Context, id pgtype.UUID) (GetPlaceListByIDRow, error) {
	row := q.db.QueryRow(ctx, getPlaceListByID, id)
	var i GetPlaceListByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.Category,
		&i.Area,
		&i.Occasions,
		&i.SortOrder,
		&i.SourceHash,
		&i.ListType,
		&i.Visibility,
		&i.SavesCount,
		&i.CityID,
		&i.CitySlug,
		&i.CityName,
		&i.CreatorUserID,
		&i.CreatorDisplayName,
		&i.CreatorUsername,
		&i.CreatorAvatarUrl,
		&i.StopsCount,
	)
	return i, err
}

const getPlaceListBySlug = `-- name: GetPlaceListBySlug :one
SELECT
  pl.id::text AS id,
  pl.slug,
  pl.title,
  pl.subtitle,
  pl.category,
  pl.area,
  pl.occasions,
  pl.sort_order,
  pl.source_hash,
  pl.list_type,
  pl.visibility,
  pl.saves_count,
  pl.city_id::text AS city_id,
  c.slug AS city_slug,
  c.name AS city_name,
  COALESCE(pl.creator_user_id::text, ''::text)::text AS creator_user_id,
  COALESCE(NULLIF(trim(concat_ws(' ', up.first_name, up.last_name)), ''), up.username::text, u.primary_email) AS creator_display_name,
  COALESCE(up.username::text, ''::text)::text AS creator_username,
  up.avatar_url AS creator_avatar_url,
  (
    SELECT COUNT(*)::integer
    FROM place_list_entries ple
    WHERE ple.list_id = pl.id
      AND ple.is_active = true
  ) AS stops_count
FROM place_lists pl
JOIN cities c ON c.id = pl.city_id
LEFT JOIN users u ON u.id = pl.creator_user_id
LEFT JOIN user_profiles up ON up.user_id = pl.creator_user_id
WHERE pl.slug = $1
  AND pl.is_active = true
`

type GetPlaceListBySlugRow struct {
	ID                 string   `json:"id"`
	Slug               string   `json:"slug"`
	Title              string   `json:"title"`
	Subtitle           string   `json:"subtitle"`
	Category           string   `json:"category"`
	Area               string   `json:"area"`
	Occasions          []string `json:"occasions"`
	SortOrder          int32    `json:"sort_order"`
	SourceHash         *string  `json:"source_hash"`
	ListType           string   `json:"list_type"`
	Visibility         string   `json:"visibility"`
	SavesCount         int32    `json:"saves_count"`
	CityID             string   `json:"city_id"`
	CitySlug           string   `json:"city_slug"`
	CityName           string   `json:"city_name"`
	CreatorUserID      string   `json:"creator_user_id"`
	CreatorDisplayName *string  `json:"creator_display_name"`
	CreatorUsername    string   `json:"creator_username"`
	CreatorAvatarUrl   *string  `json:"creator_avatar_url"`
	StopsCount         int32    `json:"stops_count"`
}

func (q *Queries) GetPlaceListBySlug(ctx context.Context, slug string) (GetPlaceListBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPlaceListBySlug, slug)
	var i GetPlaceListBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Subtitle,
		&i.Category,
		&i.Area,
		&i.Occasions,
		&i.SortOrder,
		&i.SourceHash,
		&i.ListType,
		&i.Visibility,
		&i.SavesCount,
		&i.CityID,
		&i.CitySlug,
		&i.CityName,
		&i.CreatorUserID,
		&i.CreatorDisplayName,
		&i.CreatorUsername,
		&i.CreatorAvatarUrl,
		&i.StopsCount,
	)
	return i, err
}

const listActivePlaceLists = `-- name: ListActivePlaceLists :many
SELECT
  pl.id::text AS id,
  pl.slug,
  pl.title,
  pl.category,
  pl.area,
  pl.occasions,
  pl.sort_order,
  c.slug AS city_slug,
  c.name AS city_name,
  (
    SELECT COUNT(*)::integer
    FROM place_list_entries ple
    WHERE ple.list_id = pl.id
      AND ple.is_active = true
  ) AS entry_count,
  cover.cover_image_url
FROM place_lists pl
JOIN cities c ON c.id = pl.city_id
LEFT JOIN LATERAL (
  SELECT p.cover_image_url
  FROM place_list_entries ple
  JOIN places p ON p.id = ple.place_id
  WHERE ple.list_id = pl.id
    AND ple.is_active = true
    AND p.cover_image_url IS NOT NULL
  ORDER BY ple.rank
  LIMIT 1
) cover ON true
WHERE pl.is_active = true
ORDER BY pl.sort_order, pl.title
`

type ListActivePlaceListsRow struct {
	ID            string   `json:"id"`
	Slug          string   `json:"slug"`
	Title         string   `json:"title"`
	Category      string   `json:"category"`
	Area          string   `json:"area"`
	Occasions     []string `json:"occasions"`
	SortOrder     int32    `json:"sort_order"`
	CitySlug      string   `json:"city_slug"`
	CityName      string   `json:"city_name"`
	EntryCount    int32    `json:"entry_count"`
	CoverImageUrl *string  `json:"cover_image_url"`
}

func (q *Queries) ListActivePlaceLists(ctx context.Context) ([]ListActivePlaceListsRow, error) {
	rows, err := q.db.Query(ctx, listActivePlaceLists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePlaceListsRow
	for rows.Next() {
		var i ListActivePlaceListsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Category,
			&i.Area,
			&i.Occasions,
			&i.SortOrder,
			&i.CitySlug,
			&i.CityName,
			&i.EntryCount,
			&i.CoverImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaceListEntriesByListID = `-- name: ListPlaceListEntriesByListID :many
SELECT
  ple.seed_name,
  ple.rank,
  ple.note,
  ple.time_label,
  ple.activity_type,
  COALESCE(ple.image_url, p.cover_image_url) AS image_url,
  p.id::text AS place_id,
  p.name AS place_name,
  p.google_place_id,
  p.address,
  p.neighborhood,
  p.latitude,
  p.longitude,
  p.rating_cached,
  p.price_level,
  p.cover_image_url,
  p.tags
FROM place_list_entries ple
JOIN places p ON p.id = ple.place_id
WHERE ple.list_id = $1::uuid
  AND ple.is_active = true
ORDER BY ple.rank
`

type ListPlaceListEntriesByListIDRow struct {
	SeedName      string         `json:"seed_name"`
	Rank          int32          `json:"rank"`
	Note          string         `json:"note"`
	TimeLabel     string         `json:"time_label"`
	ActivityType  string         `json:"activity_type"`
	ImageUrl      *string        `json:"image_url"`
	PlaceID       string         `json:"place_id"`
	PlaceName     string         `json:"place_name"`
	GooglePlaceID *string        `json:"google_place_id"`
	Address       *string        `json:"address"`
	Neighborhood  *string        `json:"neighborhood"`
	Latitude      pgtype.Numeric `json:"latitude"`
	Longitude     pgtype.Numeric `json:"longitude"`
	RatingCached  pgtype.Numeric `json:"rating_cached"`
	PriceLevel    *int16         `json:"price_level"`
	CoverImageUrl *string        `json:"cover_image_url"`
	Tags          []string       `json:"tags"`
}

func (q *Queries) ListPlaceListEntriesByListID(ctx context.Context, listID pgtype.UUID) ([]ListPlaceListEntriesByListIDRow, error) {
	rows, err := q.db.Query(ctx, listPlaceListEntriesByListID, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaceListEntriesByListIDRow
	for rows.Next() {
		var i ListPlaceListEntriesByListIDRow
		if err := rows.Scan(
			&i.SeedName,
			&i.Rank,
			&i.Note,
			&i.TimeLabel,
			&i.ActivityType,
			&i.ImageUrl,
			&i.PlaceID,
			&i.PlaceName,
			&i.GooglePlaceID,
			&i.Address,
			&i.Neighborhood,
			&i.Latitude,
			&i.Longitude,
			&i.RatingCached,
			&i.PriceLevel,
			&i.CoverImageUrl,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaceListEntrySeedNamesByListID = `-- name: ListPlaceListEntrySeedNamesByListID :many
SELECT seed_name
FROM place_list_entries
WHERE list_id = $1::uuid
  AND is_active = true
`

func (q *Queries) ListPlaceListEntrySeedNamesByListID(ctx context.Context, listID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listPlaceListEntrySeedNamesByListID, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var seed_name string
		if err := rows.Scan(&seed_name); err != nil {
			return nil, err
		}
		items = append(items, seed_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentSyncRuns = `-- name: ListRecentSyncRuns :many
SELECT
  id::text AS id,
  started_at,
  finished_at,
  status,
  entries_added,
  entries_skipped,
  entries_failed,
  details
FROM list_sync_runs
ORDER BY started_at DESC
LIMIT $1::integer
`

type ListRecentSyncRunsRow struct {
	ID             string             `json:"id"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	Status         string             `json:"status"`
	EntriesAdded   int32              `json:"entries_added"`
	EntriesSkipped int32              `json:"entries_skipped"`
	EntriesFailed  int32              `json:"entries_failed"`
	Details        []byte             `json:"details"`
}

func (q *Queries) ListRecentSyncRuns(ctx context.Context, limitVal int32) ([]ListRecentSyncRunsRow, error) {
	rows, err := q.db.Query(ctx, listRecentSyncRuns, limitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentSyncRunsRow
	for rows.Next() {
		var i ListRecentSyncRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.EntriesAdded,
			&i.EntriesSkipped,
			&i.EntriesFailed,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGooglePlace = `-- name: UpsertGooglePlace :one
INSERT INTO places (
  city_id,
  google_place_id,
  source,
  name,
  neighborhood,
  address,
  latitude,
  longitude,
  price_level,
  rating_cached,
  cover_image_url,
  tags,
  last_synced_at,
  is_active
)
VALUES (
  $1::uuid,
  $2,
  'google',
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  now(),
  true
)
ON CONFLICT (google_place_id) DO UPDATE
SET
  name = EXCLUDED.name,
  neighborhood = COALESCE(EXCLUDED.neighborhood, places.neighborhood),
  address = COALESCE(EXCLUDED.address, places.address),
  latitude = COALESCE(EXCLUDED.latitude, places.latitude),
  longitude = COALESCE(EXCLUDED.longitude, places.longitude),
  price_level = COALESCE(EXCLUDED.price_level, places.price_level),
  rating_cached = COALESCE(EXCLUDED.rating_cached, places.rating_cached),
  cover_image_url = COALESCE(EXCLUDED.cover_image_url, places.cover_image_url),
  tags = CASE
    WHEN cardinality(EXCLUDED.tags) > 0 THEN EXCLUDED.tags
    ELSE places.tags
  END,
  last_synced_at = now(),
  updated_at = now()
RETURNING id::text AS id
`

type UpsertGooglePlaceParams struct {
	CityID        pgtype.UUID    `json:"city_id"`
	GooglePlaceID *string        `json:"google_place_id"`
	Name          string         `json:"name"`
	Neighborhood  *string        `json:"neighborhood"`
	Address       *string        `json:"address"`
	Latitude      pgtype.Numeric `json:"latitude"`
	Longitude     pgtype.Numeric `json:"longitude"`
	PriceLevel    *int16         `json:"price_level"`
	RatingCached  pgtype.Numeric `json:"rating_cached"`
	CoverImageUrl *string        `json:"cover_image_url"`
	Tags          []string       `json:"tags"`
}

func (q *Queries) UpsertGooglePlace(ctx context.Context, arg UpsertGooglePlaceParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertGooglePlace,
		arg.CityID,
		arg.GooglePlaceID,
		arg.Name,
		arg.Neighborhood,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.PriceLevel,
		arg.RatingCached,
		arg.CoverImageUrl,
		arg.Tags,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const upsertPlaceList = `-- name: UpsertPlaceList :one
INSERT INTO place_lists (
  slug,
  title,
  category,
  area,
  occasions,
  city_id,
  sort_order,
  source_hash,
  last_synced_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6::uuid,
  $7::integer,
  $8,
  now()
)
ON CONFLICT (slug) DO UPDATE
SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  area = EXCLUDED.area,
  occasions = EXCLUDED.occasions,
  city_id = EXCLUDED.city_id,
  sort_order = EXCLUDED.sort_order,
  source_hash = EXCLUDED.source_hash,
  last_synced_at = now(),
  updated_at = now()
RETURNING id::text AS id
`

type UpsertPlaceListParams struct {
	Slug       string      `json:"slug"`
	Title      string      `json:"title"`
	Category   string      `json:"category"`
	Area       string      `json:"area"`
	Occasions  []string    `json:"occasions"`
	CityID     pgtype.UUID `json:"city_id"`
	SortOrder  int32       `json:"sort_order"`
	SourceHash *string     `json:"source_hash"`
}

func (q *Queries) UpsertPlaceList(ctx context.Context, arg UpsertPlaceListParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertPlaceList,
		arg.Slug,
		arg.Title,
		arg.Category,
		arg.Area,
		arg.Occasions,
		arg.CityID,
		arg.SortOrder,
		arg.SourceHash,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const upsertPlaceListEntry = `-- name: UpsertPlaceListEntry :exec
INSERT INTO place_list_entries (
  list_id,
  place_id,
  seed_name,
  rank,
  note,
  is_active
)
VALUES (
  $1::uuid,
  $2::uuid,
  $3,
  $4::integer,
  $5,
  true
)
ON CONFLICT (list_id, seed_name) DO UPDATE
SET
  place_id = EXCLUDED.place_id,
  rank = EXCLUDED.rank,
  note = EXCLUDED.note,
  is_active = true,
  updated_at = now()
`

type UpsertPlaceListEntryParams struct {
	ListID   pgtype.UUID `json:"list_id"`
	PlaceID  pgtype.UUID `json:"place_id"`
	SeedName string      `json:"seed_name"`
	Rank     int32       `json:"rank"`
	Note     string      `json:"note"`
}

func (q *Queries) UpsertPlaceListEntry(ctx context.Context, arg UpsertPlaceListEntryParams) error {
	_, err := q.db.Exec(ctx, upsertPlaceListEntry,
		arg.ListID,
		arg.PlaceID,
		arg.SeedName,
		arg.Rank,
		arg.Note,
	)
	return err
}
