// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                    pgtype.UUID        `json:"id"`
	PrimaryEmail          *string            `json:"primary_email"`
	EmailVerifiedAt       pgtype.Timestamptz `json:"email_verified_at"`
	PasswordHash          *string            `json:"password_hash"`
	OnboardingStatus      interface{}        `json:"onboarding_status"`
	OnboardingCompletedAt pgtype.Timestamptz `json:"onboarding_completed_at"`
	LastLoginAt           pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
}

type UserAuthIdentity struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Provider       interface{}        `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	Email          *string            `json:"email"`
	EmailVerified  bool               `json:"email_verified"`
	RawProfile     []byte             `json:"raw_profile"`
	LinkedAt       pgtype.Timestamptz `json:"linked_at"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
}

type UserFollow struct {
	FollowerUserID  pgtype.UUID        `json:"follower_user_id"`
	FollowingUserID pgtype.UUID        `json:"following_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type UserProfile struct {
	UserID              pgtype.UUID        `json:"user_id"`
	FirstName           string             `json:"first_name"`
	LastName            string             `json:"last_name"`
	Username            string             `json:"username"`
	PhoneE164           *string            `json:"phone_e164"`
	PhoneCountryCode    *string            `json:"phone_country_code"`
	PhoneNationalNumber *string            `json:"phone_national_number"`
	DateOfBirth         pgtype.Date        `json:"date_of_birth"`
	AvatarObjectKey     *string            `json:"avatar_object_key"`
	AvatarUrl           *string            `json:"avatar_url"`
	Bio                 *string            `json:"bio"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}
