// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: onboarding.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeUserOnboarding = `-- name: CompleteUserOnboarding :one
UPDATE users
SET
  onboarding_status = 'completed',
  onboarding_completed_at = now()
WHERE id = $1::uuid
RETURNING onboarding_status::text AS onboarding_status
`

func (q *Queries) CompleteUserOnboarding(ctx context.Context, userID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, completeUserOnboarding, userID)
	var onboarding_status string
	err := row.Scan(&onboarding_status)
	return onboarding_status, err
}

const countOnboardingSteps = `-- name: CountOnboardingSteps :one
SELECT COUNT(*)::integer AS step_count
FROM onboarding_steps
WHERE user_id = $1::uuid
`

func (q *Queries) CountOnboardingSteps(ctx context.Context, userID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countOnboardingSteps, userID)
	var step_count int32
	err := row.Scan(&step_count)
	return step_count, err
}

const deleteUserExploreCities = `-- name: DeleteUserExploreCities :exec
DELETE FROM user_explore_cities
WHERE user_id = $1::uuid
`

func (q *Queries) DeleteUserExploreCities(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserExploreCities, userID)
	return err
}

const deleteUserLikedPlacesBySource = `-- name: DeleteUserLikedPlacesBySource :exec
DELETE FROM user_liked_places
WHERE user_id = $1::uuid
  AND source = $2
`

type DeleteUserLikedPlacesBySourceParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Source string      `json:"source"`
}

func (q *Queries) DeleteUserLikedPlacesBySource(ctx context.Context, arg DeleteUserLikedPlacesBySourceParams) error {
	_, err := q.db.Exec(ctx, deleteUserLikedPlacesBySource, arg.UserID, arg.Source)
	return err
}

const deleteUserPurposeCategories = `-- name: DeleteUserPurposeCategories :exec
DELETE FROM user_purpose_categories
WHERE user_id = $1::uuid
`

func (q *Queries) DeleteUserPurposeCategories(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserPurposeCategories, userID)
	return err
}

const deleteUserVibes = `-- name: DeleteUserVibes :exec
DELETE FROM user_vibes
WHERE user_id = $1::uuid
`

func (q *Queries) DeleteUserVibes(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserVibes, userID)
	return err
}

const insertUserExploreCity = `-- name: InsertUserExploreCity :exec
INSERT INTO user_explore_cities (user_id, city_id, priority)
VALUES (
  $1::uuid,
  $2::uuid,
  $3::integer
)
`

type InsertUserExploreCityParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	CityID   pgtype.UUID `json:"city_id"`
	Priority int32       `json:"priority"`
}

func (q *Queries) InsertUserExploreCity(ctx context.Context, arg InsertUserExploreCityParams) error {
	_, err := q.db.Exec(ctx, insertUserExploreCity, arg.UserID, arg.CityID, arg.Priority)
	return err
}

const insertUserLikedPlace = `-- name: InsertUserLikedPlace :exec
INSERT INTO user_liked_places (user_id, place_id, source)
VALUES (
  $1::uuid,
  $2::uuid,
  $3
)
`

type InsertUserLikedPlaceParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	PlaceID pgtype.UUID `json:"place_id"`
	Source  string      `json:"source"`
}

func (q *Queries) InsertUserLikedPlace(ctx context.Context, arg InsertUserLikedPlaceParams) error {
	_, err := q.db.Exec(ctx, insertUserLikedPlace, arg.UserID, arg.PlaceID, arg.Source)
	return err
}

const insertUserPurposeCategory = `-- name: InsertUserPurposeCategory :exec
INSERT INTO user_purpose_categories (user_id, category_id)
VALUES (
  $1::uuid,
  $2::uuid
)
`

type InsertUserPurposeCategoryParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) InsertUserPurposeCategory(ctx context.Context, arg InsertUserPurposeCategoryParams) error {
	_, err := q.db.Exec(ctx, insertUserPurposeCategory, arg.UserID, arg.CategoryID)
	return err
}

const insertUserVibe = `-- name: InsertUserVibe :exec
INSERT INTO user_vibes (user_id, vibe_id, weight)
VALUES (
  $1::uuid,
  $2::uuid,
  $3::numeric
)
`

type InsertUserVibeParams struct {
	UserID pgtype.UUID    `json:"user_id"`
	VibeID pgtype.UUID    `json:"vibe_id"`
	Weight pgtype.Numeric `json:"weight"`
}

func (q *Queries) InsertUserVibe(ctx context.Context, arg InsertUserVibeParams) error {
	_, err := q.db.Exec(ctx, insertUserVibe, arg.UserID, arg.VibeID, arg.Weight)
	return err
}

const listActiveCities = `-- name: ListActiveCities :many
SELECT
  id::text AS id,
  slug,
  name,
  country_code,
  cover_image_url,
  sort_order
FROM cities
WHERE is_active = true
ORDER BY sort_order, name
`

type ListActiveCitiesRow struct {
	ID            string  `json:"id"`
	Slug          string  `json:"slug"`
	Name          string  `json:"name"`
	CountryCode   string  `json:"country_code"`
	CoverImageUrl *string `json:"cover_image_url"`
	SortOrder     int32   `json:"sort_order"`
}

func (q *Queries) ListActiveCities(ctx context.Context) ([]ListActiveCitiesRow, error) {
	rows, err := q.db.Query(ctx, listActiveCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveCitiesRow
	for rows.Next() {
		var i ListActiveCitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CountryCode,
			&i.CoverImageUrl,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePurposeCategories = `-- name: ListActivePurposeCategories :many
SELECT
  id::text AS id,
  slug,
  name,
  icon_name,
  sort_order
FROM purpose_categories
WHERE is_active = true
ORDER BY sort_order, name
`

type ListActivePurposeCategoriesRow struct {
	ID        string `json:"id"`
	Slug      string `json:"slug"`
	Name      string `json:"name"`
	IconName  string `json:"icon_name"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) ListActivePurposeCategories(ctx context.Context) ([]ListActivePurposeCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listActivePurposeCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePurposeCategoriesRow
	for rows.Next() {
		var i ListActivePurposeCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.IconName,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveVibes = `-- name: ListActiveVibes :many
SELECT
  id::text AS id,
  slug,
  name,
  description,
  sort_order
FROM vibes
WHERE is_active = true
ORDER BY sort_order, name
`

type ListActiveVibesRow struct {
	ID          string `json:"id"`
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Description string `json:"description"`
	SortOrder   int32  `json:"sort_order"`
}

func (q *Queries) ListActiveVibes(ctx context.Context) ([]ListActiveVibesRow, error) {
	rows, err := q.db.Query(ctx, listActiveVibes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveVibesRow
	for rows.Next() {
		var i ListActiveVibesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCuratedVenuesByCity = `-- name: ListCuratedVenuesByCity :many
SELECT
  p.id::text AS id,
  p.slug,
  p.name,
  COALESCE(pc.name, 'Restaurant') AS category,
  p.rating_cached,
  p.price_level,
  p.neighborhood,
  p.cover_image_url,
  p.tags
FROM places p
LEFT JOIN LATERAL (
  SELECT c.name
  FROM place_categories pc
  JOIN purpose_categories c ON c.id = pc.category_id
  WHERE pc.place_id = p.id
  ORDER BY c.sort_order
  LIMIT 1
) pc ON true
WHERE p.city_id = $1::uuid
  AND p.source = 'curated'
  AND p.is_active = true
ORDER BY p.name
`

type ListCuratedVenuesByCityRow struct {
	ID            string         `json:"id"`
	Slug          *string        `json:"slug"`
	Name          string         `json:"name"`
	Category      string         `json:"category"`
	RatingCached  pgtype.Numeric `json:"rating_cached"`
	PriceLevel    *int16         `json:"price_level"`
	Neighborhood  *string        `json:"neighborhood"`
	CoverImageUrl *string        `json:"cover_image_url"`
	Tags          []string       `json:"tags"`
}

func (q *Queries) ListCuratedVenuesByCity(ctx context.Context, cityID pgtype.UUID) ([]ListCuratedVenuesByCityRow, error) {
	rows, err := q.db.Query(ctx, listCuratedVenuesByCity, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCuratedVenuesByCityRow
	for rows.Next() {
		var i ListCuratedVenuesByCityRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Category,
			&i.RatingCached,
			&i.PriceLevel,
			&i.Neighborhood,
			&i.CoverImageUrl,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserOnboardingInProgress = `-- name: MarkUserOnboardingInProgress :exec
UPDATE users
SET onboarding_status = 'in_progress'
WHERE id = $1::uuid
  AND onboarding_status <> 'completed'
`

func (q *Queries) MarkUserOnboardingInProgress(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markUserOnboardingInProgress, userID)
	return err
}

const upsertOnboardingStep = `-- name: UpsertOnboardingStep :exec
INSERT INTO onboarding_steps (user_id, step_number, completed_at, metadata)
VALUES (
  $1::uuid,
  $2::smallint,
  now(),
  $3::jsonb
)
ON CONFLICT (user_id, step_number)
DO UPDATE SET
  completed_at = now(),
  metadata = EXCLUDED.metadata
`

type UpsertOnboardingStepParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	StepNumber int16       `json:"step_number"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) UpsertOnboardingStep(ctx context.Context, arg UpsertOnboardingStepParams) error {
	_, err := q.db.Exec(ctx, upsertOnboardingStep, arg.UserID, arg.StepNumber, arg.Metadata)
	return err
}
