// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: places.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlaceByGooglePlaceID = `-- name: GetPlaceByGooglePlaceID :one
SELECT
  p.id::text AS id,
  p.city_id::text AS city_id,
  c.slug AS city_slug,
  c.name AS city_name,
  p.google_place_id,
  p.source,
  p.name,
  p.slug,
  p.neighborhood,
  p.address,
  p.latitude,
  p.longitude,
  p.price_level,
  p.rating_cached,
  p.user_rating_count,
  p.phone,
  p.website,
  p.hours_json,
  p.photo_names,
  p.business_status,
  p.cover_image_url,
  p.tags,
  p.last_synced_at,
  p.is_active
FROM places p
JOIN cities c ON c.id = p.city_id
WHERE p.google_place_id = $1
  AND p.is_active = true
`

type GetPlaceByGooglePlaceIDRow struct {
	ID              string             `json:"id"`
	CityID          string             `json:"city_id"`
	CitySlug        string             `json:"city_slug"`
	CityName        string             `json:"city_name"`
	GooglePlaceID   *string            `json:"google_place_id"`
	Source          string             `json:"source"`
	Name            string             `json:"name"`
	Slug            *string            `json:"slug"`
	Neighborhood    *string            `json:"neighborhood"`
	Address         *string            `json:"address"`
	Latitude        pgtype.Numeric     `json:"latitude"`
	Longitude       pgtype.Numeric     `json:"longitude"`
	PriceLevel      *int16             `json:"price_level"`
	RatingCached    pgtype.Numeric     `json:"rating_cached"`
	UserRatingCount *int32             `json:"user_rating_count"`
	Phone           *string            `json:"phone"`
	Website         *string            `json:"website"`
	HoursJson       []byte             `json:"hours_json"`
	PhotoNames      []string           `json:"photo_names"`
	BusinessStatus  *string            `json:"business_status"`
	CoverImageUrl   *string            `json:"cover_image_url"`
	Tags            []string           `json:"tags"`
	LastSyncedAt    pgtype.Timestamptz `json:"last_synced_at"`
	IsActive        bool               `json:"is_active"`
}

func (q *Queries) GetPlaceByGooglePlaceID(ctx context.Context, googlePlaceID *string) (GetPlaceByGooglePlaceIDRow, error) {
	row := q.db.QueryRow(ctx, getPlaceByGooglePlaceID, googlePlaceID)
	var i GetPlaceByGooglePlaceIDRow
	err := row.Scan(
		&i.ID,
		&i.CityID,
		&i.CitySlug,
		&i.CityName,
		&i.GooglePlaceID,
		&i.Source,
		&i.Name,
		&i.Slug,
		&i.Neighborhood,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.PriceLevel,
		&i.RatingCached,
		&i.UserRatingCount,
		&i.Phone,
		&i.Website,
		&i.HoursJson,
		&i.PhotoNames,
		&i.BusinessStatus,
		&i.CoverImageUrl,
		&i.Tags,
		&i.LastSyncedAt,
		&i.IsActive,
	)
	return i, err
}

const getPlaceByID = `-- name: GetPlaceByID :one
SELECT
  p.id::text AS id,
  p.city_id::text AS city_id,
  c.slug AS city_slug,
  c.name AS city_name,
  p.google_place_id,
  p.source,
  p.name,
  p.slug,
  p.neighborhood,
  p.address,
  p.latitude,
  p.longitude,
  p.price_level,
  p.rating_cached,
  p.user_rating_count,
  p.phone,
  p.website,
  p.hours_json,
  p.photo_names,
  p.business_status,
  p.cover_image_url,
  p.tags,
  p.last_synced_at,
  p.is_active
FROM places p
JOIN cities c ON c.id = p.city_id
WHERE p.id = $1::uuid
  AND p.is_active = true
`

type GetPlaceByIDRow struct {
	ID              string             `json:"id"`
	CityID          string             `json:"city_id"`
	CitySlug        string             `json:"city_slug"`
	CityName        string             `json:"city_name"`
	GooglePlaceID   *string            `json:"google_place_id"`
	Source          string             `json:"source"`
	Name            string             `json:"name"`
	Slug            *string            `json:"slug"`
	Neighborhood    *string            `json:"neighborhood"`
	Address         *string            `json:"address"`
	Latitude        pgtype.Numeric     `json:"latitude"`
	Longitude       pgtype.Numeric     `json:"longitude"`
	PriceLevel      *int16             `json:"price_level"`
	RatingCached    pgtype.Numeric     `json:"rating_cached"`
	UserRatingCount *int32             `json:"user_rating_count"`
	Phone           *string            `json:"phone"`
	Website         *string            `json:"website"`
	HoursJson       []byte             `json:"hours_json"`
	PhotoNames      []string           `json:"photo_names"`
	BusinessStatus  *string            `json:"business_status"`
	CoverImageUrl   *string            `json:"cover_image_url"`
	Tags            []string           `json:"tags"`
	LastSyncedAt    pgtype.Timestamptz `json:"last_synced_at"`
	IsActive        bool               `json:"is_active"`
}

func (q *Queries) GetPlaceByID(ctx context.Context, id pgtype.UUID) (GetPlaceByIDRow, error) {
	row := q.db.QueryRow(ctx, getPlaceByID, id)
	var i GetPlaceByIDRow
	err := row.Scan(
		&i.ID,
		&i.CityID,
		&i.CitySlug,
		&i.CityName,
		&i.GooglePlaceID,
		&i.Source,
		&i.Name,
		&i.Slug,
		&i.Neighborhood,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.PriceLevel,
		&i.RatingCached,
		&i.UserRatingCount,
		&i.Phone,
		&i.Website,
		&i.HoursJson,
		&i.PhotoNames,
		&i.BusinessStatus,
		&i.CoverImageUrl,
		&i.Tags,
		&i.LastSyncedAt,
		&i.IsActive,
	)
	return i, err
}

const upsertPlaceFromGoogle = `-- name: UpsertPlaceFromGoogle :one
INSERT INTO places (
  city_id,
  google_place_id,
  source,
  name,
  neighborhood,
  address,
  latitude,
  longitude,
  price_level,
  rating_cached,
  user_rating_count,
  phone,
  website,
  hours_json,
  photo_names,
  business_status,
  cover_image_url,
  tags,
  last_synced_at,
  is_active
)
VALUES (
  $1::uuid,
  $2,
  'google',
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  COALESCE($14, '{}'::text[]),
  $15,
  $16,
  COALESCE($17, '{}'::text[]),
  now(),
  true
)
ON CONFLICT (google_place_id) DO UPDATE
SET
  name = EXCLUDED.name,
  neighborhood = COALESCE(EXCLUDED.neighborhood, places.neighborhood),
  address = COALESCE(EXCLUDED.address, places.address),
  latitude = COALESCE(EXCLUDED.latitude, places.latitude),
  longitude = COALESCE(EXCLUDED.longitude, places.longitude),
  price_level = COALESCE(EXCLUDED.price_level, places.price_level),
  rating_cached = COALESCE(EXCLUDED.rating_cached, places.rating_cached),
  user_rating_count = COALESCE(EXCLUDED.user_rating_count, places.user_rating_count),
  phone = COALESCE(EXCLUDED.phone, places.phone),
  website = COALESCE(EXCLUDED.website, places.website),
  hours_json = COALESCE(EXCLUDED.hours_json, places.hours_json),
  photo_names = CASE
    WHEN cardinality(EXCLUDED.photo_names) > 0 THEN EXCLUDED.photo_names
    ELSE places.photo_names
  END,
  business_status = COALESCE(EXCLUDED.business_status, places.business_status),
  cover_image_url = COALESCE(EXCLUDED.cover_image_url, places.cover_image_url),
  tags = CASE
    WHEN cardinality(EXCLUDED.tags) > 0 THEN EXCLUDED.tags
    ELSE places.tags
  END,
  last_synced_at = now(),
  updated_at = now()
RETURNING id::text AS id
`

type UpsertPlaceFromGoogleParams struct {
	CityID          pgtype.UUID    `json:"city_id"`
	GooglePlaceID   *string        `json:"google_place_id"`
	Name            string         `json:"name"`
	Neighborhood    *string        `json:"neighborhood"`
	Address         *string        `json:"address"`
	Latitude        pgtype.Numeric `json:"latitude"`
	Longitude       pgtype.Numeric `json:"longitude"`
	PriceLevel      *int16         `json:"price_level"`
	RatingCached    pgtype.Numeric `json:"rating_cached"`
	UserRatingCount *int32         `json:"user_rating_count"`
	Phone           *string        `json:"phone"`
	Website         *string        `json:"website"`
	HoursJson       []byte         `json:"hours_json"`
	PhotoNames      interface{}    `json:"photo_names"`
	BusinessStatus  *string        `json:"business_status"`
	CoverImageUrl   *string        `json:"cover_image_url"`
	Tags            interface{}    `json:"tags"`
}

func (q *Queries) UpsertPlaceFromGoogle(ctx context.Context, arg UpsertPlaceFromGoogleParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertPlaceFromGoogle,
		arg.CityID,
		arg.GooglePlaceID,
		arg.Name,
		arg.Neighborhood,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.PriceLevel,
		arg.RatingCached,
		arg.UserRatingCount,
		arg.Phone,
		arg.Website,
		arg.HoursJson,
		arg.PhotoNames,
		arg.BusinessStatus,
		arg.CoverImageUrl,
		arg.Tags,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
