// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CompleteUserOnboarding(ctx context.Context, userID pgtype.UUID) (string, error)
	CountExternalEvents(ctx context.Context, citySlug *string) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteUserExploreCities(ctx context.Context, userID pgtype.UUID) error
	DeleteUserLikedPlacesBySource(ctx context.Context, arg DeleteUserLikedPlacesBySourceParams) error
	DeleteUserPurposeCategories(ctx context.Context, userID pgtype.UUID) error
	DeleteUserVibes(ctx context.Context, userID pgtype.UUID) error
	FindUserByEmail(ctx context.Context, primaryEmail *string) (FindUserByEmailRow, error)
	FindUserByIdentity(ctx context.Context, arg FindUserByIdentityParams) (FindUserByIdentityRow, error)
	GetUserProfile(ctx context.Context, userID pgtype.UUID) (GetUserProfileRow, error)
	HasUserProfile(ctx context.Context, userID pgtype.UUID) (bool, error)
	InsertUserExploreCity(ctx context.Context, arg InsertUserExploreCityParams) error
	InsertUserLikedPlace(ctx context.Context, arg InsertUserLikedPlaceParams) error
	InsertUserPurposeCategory(ctx context.Context, arg InsertUserPurposeCategoryParams) error
	InsertUserVibe(ctx context.Context, arg InsertUserVibeParams) error
	IsUsernameTakenByAnotherUser(ctx context.Context, arg IsUsernameTakenByAnotherUserParams) (bool, error)
	ListActiveCities(ctx context.Context) ([]ListActiveCitiesRow, error)
	ListActivePurposeCategories(ctx context.Context) ([]ListActivePurposeCategoriesRow, error)
	ListActiveVibes(ctx context.Context) ([]ListActiveVibesRow, error)
	ListCuratedVenuesByCity(ctx context.Context, cityID pgtype.UUID) ([]ListCuratedVenuesByCityRow, error)
	ListExternalEvents(ctx context.Context, arg ListExternalEventsParams) ([]ListExternalEventsRow, error)
	ListUpcomingEvents(ctx context.Context, arg ListUpcomingEventsParams) ([]ListUpcomingEventsRow, error)
	UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) (UpdateLastLoginRow, error)
	UpsertIdentity(ctx context.Context, arg UpsertIdentityParams) error
	UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UpsertUserProfileRow, error)
}

var _ Querier = (*Queries)(nil)
