// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stamps.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlacePairwise = `-- name: CountPlacePairwise :one
SELECT COUNT(*)::integer AS count
FROM pairwise_comparisons
WHERE place_a_id = $1::uuid
   OR place_b_id = $1::uuid
`

func (q *Queries) CountPlacePairwise(ctx context.Context, placeID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPlacePairwise, placeID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countPlacePairwiseWins = `-- name: CountPlacePairwiseWins :one
SELECT COUNT(*)::integer AS count
FROM pairwise_comparisons
WHERE winner_place_id = $1::uuid
`

func (q *Queries) CountPlacePairwiseWins(ctx context.Context, placeID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPlacePairwiseWins, placeID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countRecentPairwisePair = `-- name: CountRecentPairwisePair :one
SELECT COUNT(*)::integer AS count
FROM pairwise_comparisons
WHERE user_id = $1::uuid
  AND (
    (place_a_id = $2::uuid AND place_b_id = $3::uuid)
    OR (place_a_id = $3::uuid AND place_b_id = $2::uuid)
  )
  AND created_at > now() - interval '30 days'
`

type CountRecentPairwisePairParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	PlaceAID pgtype.UUID `json:"place_a_id"`
	PlaceBID pgtype.UUID `json:"place_b_id"`
}

func (q *Queries) CountRecentPairwisePair(ctx context.Context, arg CountRecentPairwisePairParams) (int32, error) {
	row := q.db.QueryRow(ctx, countRecentPairwisePair, arg.UserID, arg.PlaceAID, arg.PlaceBID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createPlacementSession = `-- name: CreatePlacementSession :one
INSERT INTO placement_sessions (
  user_id,
  stamp_id,
  place_id,
  venue_category,
  band,
  lo_index,
  hi_index,
  comparisons_done,
  is_complete
)
VALUES (
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
RETURNING
  id::text AS id,
  user_id::text AS user_id,
  stamp_id::text AS stamp_id,
  place_id::text AS place_id,
  venue_category,
  band,
  lo_index,
  hi_index,
  comparisons_done,
  is_complete
`

type CreatePlacementSessionParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	StampID         pgtype.UUID `json:"stamp_id"`
	PlaceID         pgtype.UUID `json:"place_id"`
	VenueCategory   string      `json:"venue_category"`
	Band            string      `json:"band"`
	LoIndex         int32       `json:"lo_index"`
	HiIndex         int32       `json:"hi_index"`
	ComparisonsDone int32       `json:"comparisons_done"`
	IsComplete      bool        `json:"is_complete"`
}

type CreatePlacementSessionRow struct {
	ID              string `json:"id"`
	UserID          string `json:"user_id"`
	StampID         string `json:"stamp_id"`
	PlaceID         string `json:"place_id"`
	VenueCategory   string `json:"venue_category"`
	Band            string `json:"band"`
	LoIndex         int32  `json:"lo_index"`
	HiIndex         int32  `json:"hi_index"`
	ComparisonsDone int32  `json:"comparisons_done"`
	IsComplete      bool   `json:"is_complete"`
}

func (q *Queries) CreatePlacementSession(ctx context.Context, arg CreatePlacementSessionParams) (CreatePlacementSessionRow, error) {
	row := q.db.QueryRow(ctx, createPlacementSession,
		arg.UserID,
		arg.StampID,
		arg.PlaceID,
		arg.VenueCategory,
		arg.Band,
		arg.LoIndex,
		arg.HiIndex,
		arg.ComparisonsDone,
		arg.IsComplete,
	)
	var i CreatePlacementSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StampID,
		&i.PlaceID,
		&i.VenueCategory,
		&i.Band,
		&i.LoIndex,
		&i.HiIndex,
		&i.ComparisonsDone,
		&i.IsComplete,
	)
	return i, err
}

const deleteStampTags = `-- name: DeleteStampTags :exec
DELETE FROM stamp_tags
WHERE stamp_id = $1::uuid
`

func (q *Queries) DeleteStampTags(ctx context.Context, stampID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStampTags, stampID)
	return err
}

const deleteVenueTagAggregates = `-- name: DeleteVenueTagAggregates :exec
DELETE FROM venue_tag_aggregates
WHERE place_id = $1::uuid
`

func (q *Queries) DeleteVenueTagAggregates(ctx context.Context, placeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVenueTagAggregates, placeID)
	return err
}

const getActivePlacementSession = `-- name: GetActivePlacementSession :one
SELECT
  id::text AS id,
  user_id::text AS user_id,
  stamp_id::text AS stamp_id,
  place_id::text AS place_id,
  venue_category,
  band,
  lo_index,
  hi_index,
  comparisons_done,
  is_complete
FROM placement_sessions
WHERE stamp_id = $1::uuid
  AND is_complete = false
ORDER BY created_at DESC
LIMIT 1
`

type GetActivePlacementSessionRow struct {
	ID              string `json:"id"`
	UserID          string `json:"user_id"`
	StampID         string `json:"stamp_id"`
	PlaceID         string `json:"place_id"`
	VenueCategory   string `json:"venue_category"`
	Band            string `json:"band"`
	LoIndex         int32  `json:"lo_index"`
	HiIndex         int32  `json:"hi_index"`
	ComparisonsDone int32  `json:"comparisons_done"`
	IsComplete      bool   `json:"is_complete"`
}

func (q *Queries) GetActivePlacementSession(ctx context.Context, stampID pgtype.UUID) (GetActivePlacementSessionRow, error) {
	row := q.db.QueryRow(ctx, getActivePlacementSession, stampID)
	var i GetActivePlacementSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StampID,
		&i.PlaceID,
		&i.VenueCategory,
		&i.Band,
		&i.LoIndex,
		&i.HiIndex,
		&i.ComparisonsDone,
		&i.IsComplete,
	)
	return i, err
}

const getActiveStampByUserPlace = `-- name: GetActiveStampByUserPlace :one
SELECT
  id::text AS id,
  user_id::text AS user_id,
  place_id::text AS place_id,
  venue_category,
  verdict,
  quality,
  note,
  visit_count,
  verification_level,
  weight,
  device_latitude,
  device_longitude,
  created_at,
  updated_at
FROM stamps
WHERE user_id = $1::uuid
  AND place_id = $2::uuid
  AND is_active = true
`

type GetActiveStampByUserPlaceParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	PlaceID pgtype.UUID `json:"place_id"`
}

type GetActiveStampByUserPlaceRow struct {
	ID                string             `json:"id"`
	UserID            string             `json:"user_id"`
	PlaceID           string             `json:"place_id"`
	VenueCategory     string             `json:"venue_category"`
	Verdict           string             `json:"verdict"`
	Quality           string             `json:"quality"`
	Note              string             `json:"note"`
	VisitCount        int32              `json:"visit_count"`
	VerificationLevel string             `json:"verification_level"`
	Weight            pgtype.Numeric     `json:"weight"`
	DeviceLatitude    pgtype.Numeric     `json:"device_latitude"`
	DeviceLongitude   pgtype.Numeric     `json:"device_longitude"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetActiveStampByUserPlace(ctx context.Context, arg GetActiveStampByUserPlaceParams) (GetActiveStampByUserPlaceRow, error) {
	row := q.db.QueryRow(ctx, getActiveStampByUserPlace, arg.UserID, arg.PlaceID)
	var i GetActiveStampByUserPlaceRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlaceID,
		&i.VenueCategory,
		&i.Verdict,
		&i.Quality,
		&i.Note,
		&i.VisitCount,
		&i.VerificationLevel,
		&i.Weight,
		&i.DeviceLatitude,
		&i.DeviceLongitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFamiliarity = `-- name: GetFamiliarity :one
SELECT user_id::text AS user_id, place_id::text AS place_id, status
FROM user_place_familiarity
WHERE user_id = $1::uuid
  AND place_id = $2::uuid
`

type GetFamiliarityParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	PlaceID pgtype.UUID `json:"place_id"`
}

type GetFamiliarityRow struct {
	UserID  string `json:"user_id"`
	PlaceID string `json:"place_id"`
	Status  string `json:"status"`
}

func (q *Queries) GetFamiliarity(ctx context.Context, arg GetFamiliarityParams) (GetFamiliarityRow, error) {
	row := q.db.QueryRow(ctx, getFamiliarity, arg.UserID, arg.PlaceID)
	var i GetFamiliarityRow
	err := row.Scan(&i.UserID, &i.PlaceID, &i.Status)
	return i, err
}

const getRankingConfig = `-- name: GetRankingConfig :one
SELECT key, value, updated_at
FROM ranking_config
WHERE key = $1
`

func (q *Queries) GetRankingConfig(ctx context.Context, key string) (RankingConfig, error) {
	row := q.db.QueryRow(ctx, getRankingConfig, key)
	var i RankingConfig
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const getStampByID = `-- name: GetStampByID :one
SELECT
  id::text AS id,
  user_id::text AS user_id,
  place_id::text AS place_id,
  venue_category,
  verdict,
  quality,
  note,
  visit_count,
  verification_level,
  weight,
  device_latitude,
  device_longitude,
  created_at,
  updated_at
FROM stamps
WHERE id = $1::uuid
  AND is_active = true
`

type GetStampByIDRow struct {
	ID                string             `json:"id"`
	UserID            string             `json:"user_id"`
	PlaceID           string             `json:"place_id"`
	VenueCategory     string             `json:"venue_category"`
	Verdict           string             `json:"verdict"`
	Quality           string             `json:"quality"`
	Note              string             `json:"note"`
	VisitCount        int32              `json:"visit_count"`
	VerificationLevel string             `json:"verification_level"`
	Weight            pgtype.Numeric     `json:"weight"`
	DeviceLatitude    pgtype.Numeric     `json:"device_latitude"`
	DeviceLongitude   pgtype.Numeric     `json:"device_longitude"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetStampByID(ctx context.Context, id pgtype.UUID) (GetStampByIDRow, error) {
	row := q.db.QueryRow(ctx, getStampByID, id)
	var i GetStampByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlaceID,
		&i.VenueCategory,
		&i.Verdict,
		&i.Quality,
		&i.Note,
		&i.VisitCount,
		&i.VerificationLevel,
		&i.Weight,
		&i.DeviceLatitude,
		&i.DeviceLongitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStampPlaceContext = `-- name: GetStampPlaceContext :one
SELECT
  p.id::text AS id,
  p.name,
  p.city_id::text AS city_id,
  c.slug AS city_slug,
  p.neighborhood,
  p.address,
  p.latitude,
  p.longitude,
  p.price_level,
  p.cover_image_url,
  p.venue_category,
  p.venue_archetype,
  p.tags
FROM places p
JOIN cities c ON c.id = p.city_id
WHERE p.id = $1::uuid
  AND p.is_active = true
`

type GetStampPlaceContextRow struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	CityID         string         `json:"city_id"`
	CitySlug       string         `json:"city_slug"`
	Neighborhood   *string        `json:"neighborhood"`
	Address        *string        `json:"address"`
	Latitude       pgtype.Numeric `json:"latitude"`
	Longitude      pgtype.Numeric `json:"longitude"`
	PriceLevel     *int16         `json:"price_level"`
	CoverImageUrl  *string        `json:"cover_image_url"`
	VenueCategory  *string        `json:"venue_category"`
	VenueArchetype *string        `json:"venue_archetype"`
	Tags           []string       `json:"tags"`
}

func (q *Queries) GetStampPlaceContext(ctx context.Context, id pgtype.UUID) (GetStampPlaceContextRow, error) {
	row := q.db.QueryRow(ctx, getStampPlaceContext, id)
	var i GetStampPlaceContextRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CityID,
		&i.CitySlug,
		&i.Neighborhood,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.PriceLevel,
		&i.CoverImageUrl,
		&i.VenueCategory,
		&i.VenueArchetype,
		&i.Tags,
	)
	return i, err
}

const getUserPoolEntry = `-- name: GetUserPoolEntry :one
SELECT
  upe.user_id::text AS user_id,
  upe.place_id::text AS place_id,
  upe.venue_category,
  upe.band,
  upe.rank_key,
  upe.score,
  upe.placement_confidence,
  upe.comparisons_count,
  upe.contradiction_count,
  upe.is_provisional
FROM user_pool_entries upe
WHERE upe.user_id = $1::uuid
  AND upe.place_id = $2::uuid
`

type GetUserPoolEntryParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	PlaceID pgtype.UUID `json:"place_id"`
}

type GetUserPoolEntryRow struct {
	UserID              string         `json:"user_id"`
	PlaceID             string         `json:"place_id"`
	VenueCategory       string         `json:"venue_category"`
	Band                string         `json:"band"`
	RankKey             pgtype.Numeric `json:"rank_key"`
	Score               pgtype.Numeric `json:"score"`
	PlacementConfidence pgtype.Numeric `json:"placement_confidence"`
	ComparisonsCount    int32          `json:"comparisons_count"`
	ContradictionCount  int32          `json:"contradiction_count"`
	IsProvisional       bool           `json:"is_provisional"`
}

func (q *Queries) GetUserPoolEntry(ctx context.Context, arg GetUserPoolEntryParams) (GetUserPoolEntryRow, error) {
	row := q.db.QueryRow(ctx, getUserPoolEntry, arg.UserID, arg.PlaceID)
	var i GetUserPoolEntryRow
	err := row.Scan(
		&i.UserID,
		&i.PlaceID,
		&i.VenueCategory,
		&i.Band,
		&i.RankKey,
		&i.Score,
		&i.PlacementConfidence,
		&i.ComparisonsCount,
		&i.ContradictionCount,
		&i.IsProvisional,
	)
	return i, err
}

const getVenueStampAggregate = `-- name: GetVenueStampAggregate :one
SELECT
  place_id::text AS place_id,
  stamp_count,
  weighted_stamp_sum,
  sentiment_score,
  quality_score,
  pairwise_strength,
  pairwise_count,
  composite_score,
  final_score,
  display_state,
  vibe_conflict,
  quality_conflict,
  conflict_note,
  velocity_score,
  updated_at
FROM venue_stamp_aggregates
WHERE place_id = $1::uuid
`

type GetVenueStampAggregateRow struct {
	PlaceID          string             `json:"place_id"`
	StampCount       int32              `json:"stamp_count"`
	WeightedStampSum pgtype.Numeric     `json:"weighted_stamp_sum"`
	SentimentScore   pgtype.Numeric     `json:"sentiment_score"`
	QualityScore     pgtype.Numeric     `json:"quality_score"`
	PairwiseStrength pgtype.Numeric     `json:"pairwise_strength"`
	PairwiseCount    int32              `json:"pairwise_count"`
	CompositeScore   pgtype.Numeric     `json:"composite_score"`
	FinalScore       pgtype.Numeric     `json:"final_score"`
	DisplayState     string             `json:"display_state"`
	VibeConflict     bool               `json:"vibe_conflict"`
	QualityConflict  bool               `json:"quality_conflict"`
	ConflictNote     *string            `json:"conflict_note"`
	VelocityScore    pgtype.Numeric     `json:"velocity_score"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetVenueStampAggregate(ctx context.Context, placeID pgtype.UUID) (GetVenueStampAggregateRow, error) {
	row := q.db.QueryRow(ctx, getVenueStampAggregate, placeID)
	var i GetVenueStampAggregateRow
	err := row.Scan(
		&i.PlaceID,
		&i.StampCount,
		&i.WeightedStampSum,
		&i.SentimentScore,
		&i.QualityScore,
		&i.PairwiseStrength,
		&i.PairwiseCount,
		&i.CompositeScore,
		&i.FinalScore,
		&i.DisplayState,
		&i.VibeConflict,
		&i.QualityConflict,
		&i.ConflictNote,
		&i.VelocityScore,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPairwiseComparison = `-- name: InsertPairwiseComparison :one
INSERT INTO pairwise_comparisons (
  user_id,
  stamp_id,
  place_a_id,
  place_b_id,
  winner_place_id,
  venue_category,
  band,
  tier,
  comparability,
  surface
)
VALUES (
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::uuid,
  $5::uuid,
  $6,
  $7,
  $8,
  $9,
  $10
)
RETURNING id::text AS id
`

type InsertPairwiseComparisonParams struct {
	UserID        pgtype.UUID    `json:"user_id"`
	StampID       pgtype.UUID    `json:"stamp_id"`
	PlaceAID      pgtype.UUID    `json:"place_a_id"`
	PlaceBID      pgtype.UUID    `json:"place_b_id"`
	WinnerPlaceID pgtype.UUID    `json:"winner_place_id"`
	VenueCategory string         `json:"venue_category"`
	Band          string         `json:"band"`
	Tier          int32          `json:"tier"`
	Comparability pgtype.Numeric `json:"comparability"`
	Surface       string         `json:"surface"`
}

func (q *Queries) InsertPairwiseComparison(ctx context.Context, arg InsertPairwiseComparisonParams) (string, error) {
	row := q.db.QueryRow(ctx, insertPairwiseComparison,
		arg.UserID,
		arg.StampID,
		arg.PlaceAID,
		arg.PlaceBID,
		arg.WinnerPlaceID,
		arg.VenueCategory,
		arg.Band,
		arg.Tier,
		arg.Comparability,
		arg.Surface,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertStampPhoto = `-- name: InsertStampPhoto :one
INSERT INTO stamp_photos (stamp_id, storage_path, label, sort_order)
VALUES (
  $1::uuid,
  $2,
  $3,
  $4
)
RETURNING id::text AS id, stamp_id::text AS stamp_id, storage_path, label, sort_order
`

type InsertStampPhotoParams struct {
	StampID     pgtype.UUID `json:"stamp_id"`
	StoragePath string      `json:"storage_path"`
	Label       string      `json:"label"`
	SortOrder   int32       `json:"sort_order"`
}

type InsertStampPhotoRow struct {
	ID          string `json:"id"`
	StampID     string `json:"stamp_id"`
	StoragePath string `json:"storage_path"`
	Label       string `json:"label"`
	SortOrder   int32  `json:"sort_order"`
}

func (q *Queries) InsertStampPhoto(ctx context.Context, arg InsertStampPhotoParams) (InsertStampPhotoRow, error) {
	row := q.db.QueryRow(ctx, insertStampPhoto,
		arg.StampID,
		arg.StoragePath,
		arg.Label,
		arg.SortOrder,
	)
	var i InsertStampPhotoRow
	err := row.Scan(
		&i.ID,
		&i.StampID,
		&i.StoragePath,
		&i.Label,
		&i.SortOrder,
	)
	return i, err
}

const insertStampTag = `-- name: InsertStampTag :exec
INSERT INTO stamp_tags (stamp_id, tag_type, tag_slug, position, is_custom)
VALUES (
  $1::uuid,
  $2,
  $3,
  $4,
  $5
)
ON CONFLICT (stamp_id, tag_type, tag_slug) DO UPDATE
SET position = EXCLUDED.position,
    is_custom = EXCLUDED.is_custom
`

type InsertStampTagParams struct {
	StampID  pgtype.UUID `json:"stamp_id"`
	TagType  string      `json:"tag_type"`
	TagSlug  string      `json:"tag_slug"`
	Position int32       `json:"position"`
	IsCustom bool        `json:"is_custom"`
}

func (q *Queries) InsertStampTag(ctx context.Context, arg InsertStampTagParams) error {
	_, err := q.db.Exec(ctx, insertStampTag,
		arg.StampID,
		arg.TagType,
		arg.TagSlug,
		arg.Position,
		arg.IsCustom,
	)
	return err
}

const insertVenueScoreHistory = `-- name: InsertVenueScoreHistory :exec
INSERT INTO venue_score_history (
  place_id,
  snapshot_date,
  stamp_count,
  weighted_stamp_sum,
  sentiment_score,
  quality_score,
  pairwise_strength,
  composite_score,
  final_score,
  display_state
)
SELECT
  place_id,
  CURRENT_DATE,
  stamp_count,
  weighted_stamp_sum,
  sentiment_score,
  quality_score,
  pairwise_strength,
  composite_score,
  final_score,
  display_state
FROM venue_stamp_aggregates
ON CONFLICT (place_id, snapshot_date) DO UPDATE
SET
  stamp_count = EXCLUDED.stamp_count,
  weighted_stamp_sum = EXCLUDED.weighted_stamp_sum,
  sentiment_score = EXCLUDED.sentiment_score,
  quality_score = EXCLUDED.quality_score,
  pairwise_strength = EXCLUDED.pairwise_strength,
  composite_score = EXCLUDED.composite_score,
  final_score = EXCLUDED.final_score,
  display_state = EXCLUDED.display_state
`

func (q *Queries) InsertVenueScoreHistory(ctx context.Context) error {
	_, err := q.db.Exec(ctx, insertVenueScoreHistory)
	return err
}

const listAllActivePlaceIDsWithStamps = `-- name: ListAllActivePlaceIDsWithStamps :many
SELECT DISTINCT place_id::text AS place_id
FROM stamps
WHERE is_active = true
`

func (q *Queries) ListAllActivePlaceIDsWithStamps(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAllActivePlaceIDsWithStamps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var place_id string
		if err := rows.Scan(&place_id); err != nil {
			return nil, err
		}
		items = append(items, place_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCuratedPlacesForProbe = `-- name: ListCuratedPlacesForProbe :many
SELECT
  p.id::text AS id,
  p.name,
  p.neighborhood,
  p.price_level,
  p.cover_image_url,
  p.venue_category,
  p.venue_archetype,
  p.tags
FROM places p
WHERE p.is_active = true
  AND p.source = 'curated'
  AND p.venue_category = $1
  AND p.city_id = $2::uuid
  AND p.id <> $3::uuid
  AND NOT EXISTS (
    SELECT 1 FROM user_place_familiarity upf
    WHERE upf.user_id = $4::uuid
      AND upf.place_id = p.id
      AND upf.status IN ('been', 'not_been')
  )
  AND NOT EXISTS (
    SELECT 1 FROM user_pool_entries upe
    WHERE upe.user_id = $4::uuid AND upe.place_id = p.id
  )
ORDER BY p.name
LIMIT 10
`

type ListCuratedPlacesForProbeParams struct {
	VenueCategory  *string     `json:"venue_category"`
	CityID         pgtype.UUID `json:"city_id"`
	ExcludePlaceID pgtype.UUID `json:"exclude_place_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

type ListCuratedPlacesForProbeRow struct {
	ID             string   `json:"id"`
	Name           string   `json:"name"`
	Neighborhood   *string  `json:"neighborhood"`
	PriceLevel     *int16   `json:"price_level"`
	CoverImageUrl  *string  `json:"cover_image_url"`
	VenueCategory  *string  `json:"venue_category"`
	VenueArchetype *string  `json:"venue_archetype"`
	Tags           []string `json:"tags"`
}

func (q *Queries) ListCuratedPlacesForProbe(ctx context.Context, arg ListCuratedPlacesForProbeParams) ([]ListCuratedPlacesForProbeRow, error) {
	rows, err := q.db.Query(ctx, listCuratedPlacesForProbe,
		arg.VenueCategory,
		arg.CityID,
		arg.ExcludePlaceID,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCuratedPlacesForProbeRow
	for rows.Next() {
		var i ListCuratedPlacesForProbeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Neighborhood,
			&i.PriceLevel,
			&i.CoverImageUrl,
			&i.VenueCategory,
			&i.VenueArchetype,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedStamps = `-- name: ListFeedStamps :many
SELECT
  s.id::text AS stamp_id,
  s.user_id::text AS user_id,
  up.first_name,
  up.last_name,
  up.username,
  up.avatar_url,
  p.id::text AS place_id,
  p.name AS place_name,
  p.cover_image_url AS place_image_url,
  s.venue_category,
  s.verdict,
  pe.band,
  pe.score AS personal_score,
  s.note,
  COALESCE(ph.storage_path, '') AS photo_storage_path,
  s.created_at
FROM stamps s
JOIN places p ON p.id = s.place_id AND p.is_active = true
JOIN user_profiles up ON up.user_id = s.user_id
LEFT JOIN user_pool_entries pe
  ON pe.user_id = s.user_id AND pe.place_id = s.place_id
LEFT JOIN LATERAL (
  SELECT sp.storage_path
  FROM stamp_photos sp
  WHERE sp.stamp_id = s.id
  ORDER BY sp.sort_order, sp.created_at
  LIMIT 1
) ph ON true
WHERE s.is_active = true
  AND (
    s.user_id = $1::uuid
    OR s.user_id IN (
      SELECT uf.following_user_id
      FROM user_follows uf
      WHERE uf.follower_user_id = $1::uuid
    )
  )
ORDER BY s.created_at DESC
LIMIT $3::int
OFFSET $2::int
`

type ListFeedStampsParams struct {
	ViewerID  pgtype.UUID `json:"viewer_id"`
	OffsetVal int32       `json:"offset_val"`
	LimitVal  int32       `json:"limit_val"`
}

type ListFeedStampsRow struct {
	StampID          string             `json:"stamp_id"`
	UserID           string             `json:"user_id"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
	Username         string             `json:"username"`
	AvatarUrl        *string            `json:"avatar_url"`
	PlaceID          string             `json:"place_id"`
	PlaceName        string             `json:"place_name"`
	PlaceImageUrl    *string            `json:"place_image_url"`
	VenueCategory    string             `json:"venue_category"`
	Verdict          string             `json:"verdict"`
	Band             *string            `json:"band"`
	PersonalScore    pgtype.Numeric     `json:"personal_score"`
	Note             string             `json:"note"`
	PhotoStoragePath string             `json:"photo_storage_path"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListFeedStamps(ctx context.Context, arg ListFeedStampsParams) ([]ListFeedStampsRow, error) {
	rows, err := q.db.Query(ctx, listFeedStamps, arg.ViewerID, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedStampsRow
	for rows.Next() {
		var i ListFeedStampsRow
		if err := rows.Scan(
			&i.StampID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.AvatarUrl,
			&i.PlaceID,
			&i.PlaceName,
			&i.PlaceImageUrl,
			&i.VenueCategory,
			&i.Verdict,
			&i.Band,
			&i.PersonalScore,
			&i.Note,
			&i.PhotoStoragePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLikedPlacesForPairwise = `-- name: ListLikedPlacesForPairwise :many
SELECT
  p.id::text AS id,
  p.name,
  p.neighborhood,
  p.price_level,
  p.cover_image_url,
  p.venue_category,
  p.venue_archetype,
  p.tags,
  p.city_id::text AS city_id
FROM user_liked_places ulp
JOIN places p ON p.id = ulp.place_id
WHERE ulp.user_id = $1::uuid
  AND p.is_active = true
  AND p.venue_category = $2
  AND p.city_id = $3::uuid
  AND p.id <> $4::uuid
  AND NOT EXISTS (
    SELECT 1 FROM user_pool_entries upe
    WHERE upe.user_id = ulp.user_id AND upe.place_id = p.id
  )
`

type ListLikedPlacesForPairwiseParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	VenueCategory  *string     `json:"venue_category"`
	CityID         pgtype.UUID `json:"city_id"`
	ExcludePlaceID pgtype.UUID `json:"exclude_place_id"`
}

type ListLikedPlacesForPairwiseRow struct {
	ID             string   `json:"id"`
	Name           string   `json:"name"`
	Neighborhood   *string  `json:"neighborhood"`
	PriceLevel     *int16   `json:"price_level"`
	CoverImageUrl  *string  `json:"cover_image_url"`
	VenueCategory  *string  `json:"venue_category"`
	VenueArchetype *string  `json:"venue_archetype"`
	Tags           []string `json:"tags"`
	CityID         string   `json:"city_id"`
}

func (q *Queries) ListLikedPlacesForPairwise(ctx context.Context, arg ListLikedPlacesForPairwiseParams) ([]ListLikedPlacesForPairwiseRow, error) {
	rows, err := q.db.Query(ctx, listLikedPlacesForPairwise,
		arg.UserID,
		arg.VenueCategory,
		arg.CityID,
		arg.ExcludePlaceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLikedPlacesForPairwiseRow
	for rows.Next() {
		var i ListLikedPlacesForPairwiseRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Neighborhood,
			&i.PriceLevel,
			&i.CoverImageUrl,
			&i.VenueCategory,
			&i.VenueArchetype,
			&i.Tags,
			&i.CityID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLowConfidencePoolEntries = `-- name: ListLowConfidencePoolEntries :many
SELECT
  upe.user_id::text AS user_id,
  upe.place_id::text AS place_id,
  upe.venue_category,
  upe.band,
  upe.rank_key,
  upe.score,
  upe.placement_confidence,
  upe.comparisons_count,
  p.name AS place_name,
  p.neighborhood,
  p.cover_image_url,
  p.venue_archetype,
  p.price_level,
  p.tags
FROM user_pool_entries upe
JOIN places p ON p.id = upe.place_id
WHERE upe.user_id = $1::uuid
  AND upe.placement_confidence < 1
  AND upe.is_provisional = false
ORDER BY upe.placement_confidence ASC, upe.updated_at ASC
LIMIT $2::integer
`

type ListLowConfidencePoolEntriesParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	LimitVal int32       `json:"limit_val"`
}

type ListLowConfidencePoolEntriesRow struct {
	UserID              string         `json:"user_id"`
	PlaceID             string         `json:"place_id"`
	VenueCategory       string         `json:"venue_category"`
	Band                string         `json:"band"`
	RankKey             pgtype.Numeric `json:"rank_key"`
	Score               pgtype.Numeric `json:"score"`
	PlacementConfidence pgtype.Numeric `json:"placement_confidence"`
	ComparisonsCount    int32          `json:"comparisons_count"`
	PlaceName           string         `json:"place_name"`
	Neighborhood        *string        `json:"neighborhood"`
	CoverImageUrl       *string        `json:"cover_image_url"`
	VenueArchetype      *string        `json:"venue_archetype"`
	PriceLevel          *int16         `json:"price_level"`
	Tags                []string       `json:"tags"`
}

func (q *Queries) ListLowConfidencePoolEntries(ctx context.Context, arg ListLowConfidencePoolEntriesParams) ([]ListLowConfidencePoolEntriesRow, error) {
	rows, err := q.db.Query(ctx, listLowConfidencePoolEntries, arg.UserID, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLowConfidencePoolEntriesRow
	for rows.Next() {
		var i ListLowConfidencePoolEntriesRow
		if err := rows.Scan(
			&i.UserID,
			&i.PlaceID,
			&i.VenueCategory,
			&i.Band,
			&i.RankKey,
			&i.Score,
			&i.PlacementConfidence,
			&i.ComparisonsCount,
			&i.PlaceName,
			&i.Neighborhood,
			&i.CoverImageUrl,
			&i.VenueArchetype,
			&i.PriceLevel,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaceStampsForAggregate = `-- name: ListPlaceStampsForAggregate :many
SELECT
  s.id::text AS id,
  s.verdict,
  s.quality,
  s.weight,
  s.created_at
FROM stamps s
WHERE s.place_id = $1::uuid
  AND s.is_active = true
`

type ListPlaceStampsForAggregateRow struct {
	ID        string             `json:"id"`
	Verdict   string             `json:"verdict"`
	Quality   string             `json:"quality"`
	Weight    pgtype.Numeric     `json:"weight"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPlaceStampsForAggregate(ctx context.Context, placeID pgtype.UUID) ([]ListPlaceStampsForAggregateRow, error) {
	rows, err := q.db.Query(ctx, listPlaceStampsForAggregate, placeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaceStampsForAggregateRow
	for rows.Next() {
		var i ListPlaceStampsForAggregateRow
		if err := rows.Scan(
			&i.ID,
			&i.Verdict,
			&i.Quality,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaceTagVotes = `-- name: ListPlaceTagVotes :many
SELECT
  st.tag_type,
  st.tag_slug,
  st.is_custom,
  s.weight
FROM stamp_tags st
JOIN stamps s ON s.id = st.stamp_id
WHERE s.place_id = $1::uuid
  AND s.is_active = true
`

type ListPlaceTagVotesRow struct {
	TagType  string         `json:"tag_type"`
	TagSlug  string         `json:"tag_slug"`
	IsCustom bool           `json:"is_custom"`
	Weight   pgtype.Numeric `json:"weight"`
}

func (q *Queries) ListPlaceTagVotes(ctx context.Context, placeID pgtype.UUID) ([]ListPlaceTagVotesRow, error) {
	rows, err := q.db.Query(ctx, listPlaceTagVotes, placeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaceTagVotesRow
	for rows.Next() {
		var i ListPlaceTagVotesRow
		if err := rows.Scan(
			&i.TagType,
			&i.TagSlug,
			&i.IsCustom,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRankingConfig = `-- name: ListRankingConfig :many
SELECT key, value, updated_at
FROM ranking_config
ORDER BY key
`

func (q *Queries) ListRankingConfig(ctx context.Context) ([]RankingConfig, error) {
	rows, err := q.db.Query(ctx, listRankingConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RankingConfig
	for rows.Next() {
		var i RankingConfig
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStampPhotos = `-- name: ListStampPhotos :many
SELECT id::text AS id, stamp_id::text AS stamp_id, storage_path, label, sort_order
FROM stamp_photos
WHERE stamp_id = $1::uuid
ORDER BY sort_order, created_at
`

type ListStampPhotosRow struct {
	ID          string `json:"id"`
	StampID     string `json:"stamp_id"`
	StoragePath string `json:"storage_path"`
	Label       string `json:"label"`
	SortOrder   int32  `json:"sort_order"`
}

func (q *Queries) ListStampPhotos(ctx context.Context, stampID pgtype.UUID) ([]ListStampPhotosRow, error) {
	rows, err := q.db.Query(ctx, listStampPhotos, stampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStampPhotosRow
	for rows.Next() {
		var i ListStampPhotosRow
		if err := rows.Scan(
			&i.ID,
			&i.StampID,
			&i.StoragePath,
			&i.Label,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStampTags = `-- name: ListStampTags :many
SELECT stamp_id::text AS stamp_id, tag_type, tag_slug, position, is_custom
FROM stamp_tags
WHERE stamp_id = $1::uuid
ORDER BY tag_type, position, tag_slug
`

type ListStampTagsRow struct {
	StampID  string `json:"stamp_id"`
	TagType  string `json:"tag_type"`
	TagSlug  string `json:"tag_slug"`
	Position int32  `json:"position"`
	IsCustom bool   `json:"is_custom"`
}

func (q *Queries) ListStampTags(ctx context.Context, stampID pgtype.UUID) ([]ListStampTagsRow, error) {
	rows, err := q.db.Query(ctx, listStampTags, stampID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStampTagsRow
	for rows.Next() {
		var i ListStampTagsRow
		if err := rows.Scan(
			&i.StampID,
			&i.TagType,
			&i.TagSlug,
			&i.Position,
			&i.IsCustom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPoolBand = `-- name: ListUserPoolBand :many
SELECT
  upe.user_id::text AS user_id,
  upe.place_id::text AS place_id,
  upe.venue_category,
  upe.band,
  upe.rank_key,
  upe.score,
  upe.placement_confidence,
  upe.comparisons_count,
  upe.contradiction_count,
  upe.is_provisional,
  p.name AS place_name,
  p.neighborhood,
  p.price_level,
  p.cover_image_url,
  p.venue_archetype,
  p.tags
FROM user_pool_entries upe
JOIN places p ON p.id = upe.place_id
WHERE upe.user_id = $1::uuid
  AND upe.venue_category = $2
  AND upe.band = $3
ORDER BY upe.rank_key ASC
`

type ListUserPoolBandParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	VenueCategory string      `json:"venue_category"`
	Band          string      `json:"band"`
}

type ListUserPoolBandRow struct {
	UserID              string         `json:"user_id"`
	PlaceID             string         `json:"place_id"`
	VenueCategory       string         `json:"venue_category"`
	Band                string         `json:"band"`
	RankKey             pgtype.Numeric `json:"rank_key"`
	Score               pgtype.Numeric `json:"score"`
	PlacementConfidence pgtype.Numeric `json:"placement_confidence"`
	ComparisonsCount    int32          `json:"comparisons_count"`
	ContradictionCount  int32          `json:"contradiction_count"`
	IsProvisional       bool           `json:"is_provisional"`
	PlaceName           string         `json:"place_name"`
	Neighborhood        *string        `json:"neighborhood"`
	PriceLevel          *int16         `json:"price_level"`
	CoverImageUrl       *string        `json:"cover_image_url"`
	VenueArchetype      *string        `json:"venue_archetype"`
	Tags                []string       `json:"tags"`
}

func (q *Queries) ListUserPoolBand(ctx context.Context, arg ListUserPoolBandParams) ([]ListUserPoolBandRow, error) {
	rows, err := q.db.Query(ctx, listUserPoolBand, arg.UserID, arg.VenueCategory, arg.Band)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserPoolBandRow
	for rows.Next() {
		var i ListUserPoolBandRow
		if err := rows.Scan(
			&i.UserID,
			&i.PlaceID,
			&i.VenueCategory,
			&i.Band,
			&i.RankKey,
			&i.Score,
			&i.PlacementConfidence,
			&i.ComparisonsCount,
			&i.ContradictionCount,
			&i.IsProvisional,
			&i.PlaceName,
			&i.Neighborhood,
			&i.PriceLevel,
			&i.CoverImageUrl,
			&i.VenueArchetype,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPoolByCategory = `-- name: ListUserPoolByCategory :many
SELECT
  upe.user_id::text AS user_id,
  upe.place_id::text AS place_id,
  upe.venue_category,
  upe.band,
  upe.rank_key,
  upe.score,
  upe.placement_confidence,
  upe.comparisons_count,
  upe.contradiction_count,
  upe.is_provisional,
  p.name AS place_name,
  p.neighborhood,
  p.price_level,
  p.cover_image_url,
  p.venue_archetype,
  p.tags
FROM user_pool_entries upe
JOIN places p ON p.id = upe.place_id
WHERE upe.user_id = $1::uuid
  AND upe.venue_category = $2
ORDER BY
  CASE upe.band
    WHEN 'must-repeat' THEN 1
    WHEN 'good-pick' THEN 2
    WHEN 'mid' THEN 3
    ELSE 4
  END,
  upe.rank_key ASC
`

type ListUserPoolByCategoryParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	VenueCategory string      `json:"venue_category"`
}

type ListUserPoolByCategoryRow struct {
	UserID              string         `json:"user_id"`
	PlaceID             string         `json:"place_id"`
	VenueCategory       string         `json:"venue_category"`
	Band                string         `json:"band"`
	RankKey             pgtype.Numeric `json:"rank_key"`
	Score               pgtype.Numeric `json:"score"`
	PlacementConfidence pgtype.Numeric `json:"placement_confidence"`
	ComparisonsCount    int32          `json:"comparisons_count"`
	ContradictionCount  int32          `json:"contradiction_count"`
	IsProvisional       bool           `json:"is_provisional"`
	PlaceName           string         `json:"place_name"`
	Neighborhood        *string        `json:"neighborhood"`
	PriceLevel          *int16         `json:"price_level"`
	CoverImageUrl       *string        `json:"cover_image_url"`
	VenueArchetype      *string        `json:"venue_archetype"`
	Tags                []string       `json:"tags"`
}

func (q *Queries) ListUserPoolByCategory(ctx context.Context, arg ListUserPoolByCategoryParams) ([]ListUserPoolByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listUserPoolByCategory, arg.UserID, arg.VenueCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserPoolByCategoryRow
	for rows.Next() {
		var i ListUserPoolByCategoryRow
		if err := rows.Scan(
			&i.UserID,
			&i.PlaceID,
			&i.VenueCategory,
			&i.Band,
			&i.RankKey,
			&i.Score,
			&i.PlacementConfidence,
			&i.ComparisonsCount,
			&i.ContradictionCount,
			&i.IsProvisional,
			&i.PlaceName,
			&i.Neighborhood,
			&i.PriceLevel,
			&i.CoverImageUrl,
			&i.VenueArchetype,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenueTagAggregates = `-- name: ListVenueTagAggregates :many
SELECT
  place_id::text AS place_id,
  tag_type,
  tag_slug,
  weighted_count,
  raw_count,
  percentage
FROM venue_tag_aggregates
WHERE place_id = $1::uuid
ORDER BY tag_type, percentage DESC, tag_slug
`

type ListVenueTagAggregatesRow struct {
	PlaceID       string         `json:"place_id"`
	TagType       string         `json:"tag_type"`
	TagSlug       string         `json:"tag_slug"`
	WeightedCount pgtype.Numeric `json:"weighted_count"`
	RawCount      int32          `json:"raw_count"`
	Percentage    pgtype.Numeric `json:"percentage"`
}

func (q *Queries) ListVenueTagAggregates(ctx context.Context, placeID pgtype.UUID) ([]ListVenueTagAggregatesRow, error) {
	rows, err := q.db.Query(ctx, listVenueTagAggregates, placeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVenueTagAggregatesRow
	for rows.Next() {
		var i ListVenueTagAggregatesRow
		if err := rows.Scan(
			&i.PlaceID,
			&i.TagType,
			&i.TagSlug,
			&i.WeightedCount,
			&i.RawCount,
			&i.Percentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumBandComparability = `-- name: SumBandComparability :one
SELECT COALESCE(SUM(comparability), 0)::float8 AS total
FROM pairwise_comparisons
WHERE user_id = $1::uuid
  AND venue_category = $2
  AND band = $3
`

type SumBandComparabilityParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	VenueCategory string      `json:"venue_category"`
	Band          string      `json:"band"`
}

func (q *Queries) SumBandComparability(ctx context.Context, arg SumBandComparabilityParams) (float64, error) {
	row := q.db.QueryRow(ctx, sumBandComparability, arg.UserID, arg.VenueCategory, arg.Band)
	var total float64
	err := row.Scan(&total)
	return total, err
}

const updatePlacementSession = `-- name: UpdatePlacementSession :one
UPDATE placement_sessions
SET lo_index = $1,
    hi_index = $2,
    comparisons_done = $3,
    is_complete = $4,
    updated_at = now()
WHERE id = $5::uuid
RETURNING
  id::text AS id,
  user_id::text AS user_id,
  stamp_id::text AS stamp_id,
  place_id::text AS place_id,
  venue_category,
  band,
  lo_index,
  hi_index,
  comparisons_done,
  is_complete
`

type UpdatePlacementSessionParams struct {
	LoIndex         int32       `json:"lo_index"`
	HiIndex         int32       `json:"hi_index"`
	ComparisonsDone int32       `json:"comparisons_done"`
	IsComplete      bool        `json:"is_complete"`
	ID              pgtype.UUID `json:"id"`
}

type UpdatePlacementSessionRow struct {
	ID              string `json:"id"`
	UserID          string `json:"user_id"`
	StampID         string `json:"stamp_id"`
	PlaceID         string `json:"place_id"`
	VenueCategory   string `json:"venue_category"`
	Band            string `json:"band"`
	LoIndex         int32  `json:"lo_index"`
	HiIndex         int32  `json:"hi_index"`
	ComparisonsDone int32  `json:"comparisons_done"`
	IsComplete      bool   `json:"is_complete"`
}

func (q *Queries) UpdatePlacementSession(ctx context.Context, arg UpdatePlacementSessionParams) (UpdatePlacementSessionRow, error) {
	row := q.db.QueryRow(ctx, updatePlacementSession,
		arg.LoIndex,
		arg.HiIndex,
		arg.ComparisonsDone,
		arg.IsComplete,
		arg.ID,
	)
	var i UpdatePlacementSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StampID,
		&i.PlaceID,
		&i.VenueCategory,
		&i.Band,
		&i.LoIndex,
		&i.HiIndex,
		&i.ComparisonsDone,
		&i.IsComplete,
	)
	return i, err
}

const updateUserPoolEntryScores = `-- name: UpdateUserPoolEntryScores :exec
UPDATE user_pool_entries
SET rank_key = $1,
    score = $2,
    placement_confidence = $3,
    comparisons_count = $4,
    contradiction_count = $5,
    updated_at = now()
WHERE user_id = $6::uuid
  AND place_id = $7::uuid
`

type UpdateUserPoolEntryScoresParams struct {
	RankKey             pgtype.Numeric `json:"rank_key"`
	Score               pgtype.Numeric `json:"score"`
	PlacementConfidence pgtype.Numeric `json:"placement_confidence"`
	ComparisonsCount    int32          `json:"comparisons_count"`
	ContradictionCount  int32          `json:"contradiction_count"`
	UserID              pgtype.UUID    `json:"user_id"`
	PlaceID             pgtype.UUID    `json:"place_id"`
}

func (q *Queries) UpdateUserPoolEntryScores(ctx context.Context, arg UpdateUserPoolEntryScoresParams) error {
	_, err := q.db.Exec(ctx, updateUserPoolEntryScores,
		arg.RankKey,
		arg.Score,
		arg.PlacementConfidence,
		arg.ComparisonsCount,
		arg.ContradictionCount,
		arg.UserID,
		arg.PlaceID,
	)
	return err
}

const upsertFamiliarity = `-- name: UpsertFamiliarity :exec
INSERT INTO user_place_familiarity (user_id, place_id, status)
VALUES (
  $1::uuid,
  $2::uuid,
  $3
)
ON CONFLICT (user_id, place_id) DO UPDATE
SET status = EXCLUDED.status,
    updated_at = now()
`

type UpsertFamiliarityParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	PlaceID pgtype.UUID `json:"place_id"`
	Status  string      `json:"status"`
}

func (q *Queries) UpsertFamiliarity(ctx context.Context, arg UpsertFamiliarityParams) error {
	_, err := q.db.Exec(ctx, upsertFamiliarity, arg.UserID, arg.PlaceID, arg.Status)
	return err
}

const upsertStamp = `-- name: UpsertStamp :one
INSERT INTO stamps (
  user_id,
  place_id,
  venue_category,
  verdict,
  quality,
  note,
  visit_count,
  verification_level,
  weight,
  device_latitude,
  device_longitude,
  is_active
)
VALUES (
  $1::uuid,
  $2::uuid,
  $3,
  $4,
  $5,
  COALESCE($6, ''),
  1,
  $7,
  $8,
  $9,
  $10,
  true
)
ON CONFLICT (user_id, place_id) WHERE is_active = true
DO UPDATE SET
  venue_category = EXCLUDED.venue_category,
  verdict = EXCLUDED.verdict,
  quality = EXCLUDED.quality,
  note = EXCLUDED.note,
  visit_count = stamps.visit_count + 1,
  verification_level = EXCLUDED.verification_level,
  weight = EXCLUDED.weight,
  device_latitude = EXCLUDED.device_latitude,
  device_longitude = EXCLUDED.device_longitude,
  updated_at = now()
RETURNING
  id::text AS id,
  user_id::text AS user_id,
  place_id::text AS place_id,
  venue_category,
  verdict,
  quality,
  note,
  visit_count,
  verification_level,
  weight,
  device_latitude,
  device_longitude,
  created_at,
  updated_at
`

type UpsertStampParams struct {
	UserID            pgtype.UUID    `json:"user_id"`
	PlaceID           pgtype.UUID    `json:"place_id"`
	VenueCategory     string         `json:"venue_category"`
	Verdict           string         `json:"verdict"`
	Quality           string         `json:"quality"`
	Note              interface{}    `json:"note"`
	VerificationLevel string         `json:"verification_level"`
	Weight            pgtype.Numeric `json:"weight"`
	DeviceLatitude    pgtype.Numeric `json:"device_latitude"`
	DeviceLongitude   pgtype.Numeric `json:"device_longitude"`
}

type UpsertStampRow struct {
	ID                string             `json:"id"`
	UserID            string             `json:"user_id"`
	PlaceID           string             `json:"place_id"`
	VenueCategory     string             `json:"venue_category"`
	Verdict           string             `json:"verdict"`
	Quality           string             `json:"quality"`
	Note              string             `json:"note"`
	VisitCount        int32              `json:"visit_count"`
	VerificationLevel string             `json:"verification_level"`
	Weight            pgtype.Numeric     `json:"weight"`
	DeviceLatitude    pgtype.Numeric     `json:"device_latitude"`
	DeviceLongitude   pgtype.Numeric     `json:"device_longitude"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertStamp(ctx context.Context, arg UpsertStampParams) (UpsertStampRow, error) {
	row := q.db.QueryRow(ctx, upsertStamp,
		arg.UserID,
		arg.PlaceID,
		arg.VenueCategory,
		arg.Verdict,
		arg.Quality,
		arg.Note,
		arg.VerificationLevel,
		arg.Weight,
		arg.DeviceLatitude,
		arg.DeviceLongitude,
	)
	var i UpsertStampRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlaceID,
		&i.VenueCategory,
		&i.Verdict,
		&i.Quality,
		&i.Note,
		&i.VisitCount,
		&i.VerificationLevel,
		&i.Weight,
		&i.DeviceLatitude,
		&i.DeviceLongitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserPoolEntry = `-- name: UpsertUserPoolEntry :one
INSERT INTO user_pool_entries (
  user_id,
  place_id,
  venue_category,
  band,
  rank_key,
  score,
  placement_confidence,
  comparisons_count,
  contradiction_count,
  is_provisional
)
VALUES (
  $1::uuid,
  $2::uuid,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
ON CONFLICT (user_id, place_id) DO UPDATE
SET
  venue_category = EXCLUDED.venue_category,
  band = EXCLUDED.band,
  rank_key = EXCLUDED.rank_key,
  score = EXCLUDED.score,
  placement_confidence = EXCLUDED.placement_confidence,
  comparisons_count = EXCLUDED.comparisons_count,
  contradiction_count = EXCLUDED.contradiction_count,
  is_provisional = EXCLUDED.is_provisional,
  updated_at = now()
RETURNING
  user_id::text AS user_id,
  place_id::text AS place_id,
  venue_category,
  band,
  rank_key,
  score,
  placement_confidence,
  comparisons_count,
  contradiction_count,
  is_provisional
`

type UpsertUserPoolEntryParams struct {
	UserID              pgtype.UUID    `json:"user_id"`
	PlaceID             pgtype.UUID    `json:"place_id"`
	VenueCategory       string         `json:"venue_category"`
	Band                string         `json:"band"`
	RankKey             pgtype.Numeric `json:"rank_key"`
	Score               pgtype.Numeric `json:"score"`
	PlacementConfidence pgtype.Numeric `json:"placement_confidence"`
	ComparisonsCount    int32          `json:"comparisons_count"`
	ContradictionCount  int32          `json:"contradiction_count"`
	IsProvisional       bool           `json:"is_provisional"`
}

type UpsertUserPoolEntryRow struct {
	UserID              string         `json:"user_id"`
	PlaceID             string         `json:"place_id"`
	VenueCategory       string         `json:"venue_category"`
	Band                string         `json:"band"`
	RankKey             pgtype.Numeric `json:"rank_key"`
	Score               pgtype.Numeric `json:"score"`
	PlacementConfidence pgtype.Numeric `json:"placement_confidence"`
	ComparisonsCount    int32          `json:"comparisons_count"`
	ContradictionCount  int32          `json:"contradiction_count"`
	IsProvisional       bool           `json:"is_provisional"`
}

func (q *Queries) UpsertUserPoolEntry(ctx context.Context, arg UpsertUserPoolEntryParams) (UpsertUserPoolEntryRow, error) {
	row := q.db.QueryRow(ctx, upsertUserPoolEntry,
		arg.UserID,
		arg.PlaceID,
		arg.VenueCategory,
		arg.Band,
		arg.RankKey,
		arg.Score,
		arg.PlacementConfidence,
		arg.ComparisonsCount,
		arg.ContradictionCount,
		arg.IsProvisional,
	)
	var i UpsertUserPoolEntryRow
	err := row.Scan(
		&i.UserID,
		&i.PlaceID,
		&i.VenueCategory,
		&i.Band,
		&i.RankKey,
		&i.Score,
		&i.PlacementConfidence,
		&i.ComparisonsCount,
		&i.ContradictionCount,
		&i.IsProvisional,
	)
	return i, err
}

const upsertVenueStampAggregate = `-- name: UpsertVenueStampAggregate :exec
INSERT INTO venue_stamp_aggregates (
  place_id,
  stamp_count,
  weighted_stamp_sum,
  sentiment_score,
  quality_score,
  pairwise_strength,
  pairwise_count,
  composite_score,
  final_score,
  display_state,
  vibe_conflict,
  quality_conflict,
  conflict_note,
  velocity_score
)
VALUES (
  $1::uuid,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14
)
ON CONFLICT (place_id) DO UPDATE
SET
  stamp_count = EXCLUDED.stamp_count,
  weighted_stamp_sum = EXCLUDED.weighted_stamp_sum,
  sentiment_score = EXCLUDED.sentiment_score,
  quality_score = EXCLUDED.quality_score,
  pairwise_strength = EXCLUDED.pairwise_strength,
  pairwise_count = EXCLUDED.pairwise_count,
  composite_score = EXCLUDED.composite_score,
  final_score = EXCLUDED.final_score,
  display_state = EXCLUDED.display_state,
  vibe_conflict = EXCLUDED.vibe_conflict,
  quality_conflict = EXCLUDED.quality_conflict,
  conflict_note = EXCLUDED.conflict_note,
  velocity_score = EXCLUDED.velocity_score,
  updated_at = now()
`

type UpsertVenueStampAggregateParams struct {
	PlaceID          pgtype.UUID    `json:"place_id"`
	StampCount       int32          `json:"stamp_count"`
	WeightedStampSum pgtype.Numeric `json:"weighted_stamp_sum"`
	SentimentScore   pgtype.Numeric `json:"sentiment_score"`
	QualityScore     pgtype.Numeric `json:"quality_score"`
	PairwiseStrength pgtype.Numeric `json:"pairwise_strength"`
	PairwiseCount    int32          `json:"pairwise_count"`
	CompositeScore   pgtype.Numeric `json:"composite_score"`
	FinalScore       pgtype.Numeric `json:"final_score"`
	DisplayState     string         `json:"display_state"`
	VibeConflict     bool           `json:"vibe_conflict"`
	QualityConflict  bool           `json:"quality_conflict"`
	ConflictNote     *string        `json:"conflict_note"`
	VelocityScore    pgtype.Numeric `json:"velocity_score"`
}

func (q *Queries) UpsertVenueStampAggregate(ctx context.Context, arg UpsertVenueStampAggregateParams) error {
	_, err := q.db.Exec(ctx, upsertVenueStampAggregate,
		arg.PlaceID,
		arg.StampCount,
		arg.WeightedStampSum,
		arg.SentimentScore,
		arg.QualityScore,
		arg.PairwiseStrength,
		arg.PairwiseCount,
		arg.CompositeScore,
		arg.FinalScore,
		arg.DisplayState,
		arg.VibeConflict,
		arg.QualityConflict,
		arg.ConflictNote,
		arg.VelocityScore,
	)
	return err
}

const upsertVenueTagAggregate = `-- name: UpsertVenueTagAggregate :exec
INSERT INTO venue_tag_aggregates (
  place_id, tag_type, tag_slug, weighted_count, raw_count, percentage
)
VALUES (
  $1::uuid,
  $2,
  $3,
  $4,
  $5,
  $6
)
ON CONFLICT (place_id, tag_type, tag_slug) DO UPDATE
SET
  weighted_count = EXCLUDED.weighted_count,
  raw_count = EXCLUDED.raw_count,
  percentage = EXCLUDED.percentage,
  updated_at = now()
`

type UpsertVenueTagAggregateParams struct {
	PlaceID       pgtype.UUID    `json:"place_id"`
	TagType       string         `json:"tag_type"`
	TagSlug       string         `json:"tag_slug"`
	WeightedCount pgtype.Numeric `json:"weighted_count"`
	RawCount      int32          `json:"raw_count"`
	Percentage    pgtype.Numeric `json:"percentage"`
}

func (q *Queries) UpsertVenueTagAggregate(ctx context.Context, arg UpsertVenueTagAggregateParams) error {
	_, err := q.db.Exec(ctx, upsertVenueTagAggregate,
		arg.PlaceID,
		arg.TagType,
		arg.TagSlug,
		arg.WeightedCount,
		arg.RawCount,
		arg.Percentage,
	)
	return err
}
