// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (primary_email, email_verified_at)
VALUES ($1, CASE WHEN $2::boolean THEN now() ELSE NULL END)
RETURNING
  id::text AS id,
  primary_email,
  email_verified_at,
  onboarding_status::text AS onboarding_status,
  last_login_at,
  created_at,
  updated_at
`

type CreateUserParams struct {
	PrimaryEmail  *string `json:"primary_email"`
	EmailVerified bool    `json:"email_verified"`
}

type CreateUserRow struct {
	ID               string             `json:"id"`
	PrimaryEmail     *string            `json:"primary_email"`
	EmailVerifiedAt  pgtype.Timestamptz `json:"email_verified_at"`
	OnboardingStatus string             `json:"onboarding_status"`
	LastLoginAt      pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.PrimaryEmail, arg.EmailVerified)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.PrimaryEmail,
		&i.EmailVerifiedAt,
		&i.OnboardingStatus,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT
  id::text AS id,
  primary_email,
  email_verified_at,
  onboarding_status::text AS onboarding_status,
  last_login_at,
  created_at,
  updated_at
FROM users
WHERE primary_email = $1
  AND deleted_at IS NULL
`

type FindUserByEmailRow struct {
	ID               string             `json:"id"`
	PrimaryEmail     *string            `json:"primary_email"`
	EmailVerifiedAt  pgtype.Timestamptz `json:"email_verified_at"`
	OnboardingStatus string             `json:"onboarding_status"`
	LastLoginAt      pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FindUserByEmail(ctx context.Context, primaryEmail *string) (FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, primaryEmail)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.PrimaryEmail,
		&i.EmailVerifiedAt,
		&i.OnboardingStatus,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByIdentity = `-- name: FindUserByIdentity :one
SELECT
  u.id::text AS id,
  u.primary_email,
  u.email_verified_at,
  u.onboarding_status::text AS onboarding_status,
  u.last_login_at,
  u.created_at,
  u.updated_at
FROM user_auth_identities i
JOIN users u ON u.id = i.user_id
WHERE i.provider = $1::auth_provider
  AND i.provider_user_id = $2
  AND u.deleted_at IS NULL
`

type FindUserByIdentityParams struct {
	Provider       interface{} `json:"provider"`
	ProviderUserID string      `json:"provider_user_id"`
}

type FindUserByIdentityRow struct {
	ID               string             `json:"id"`
	PrimaryEmail     *string            `json:"primary_email"`
	EmailVerifiedAt  pgtype.Timestamptz `json:"email_verified_at"`
	OnboardingStatus string             `json:"onboarding_status"`
	LastLoginAt      pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FindUserByIdentity(ctx context.Context, arg FindUserByIdentityParams) (FindUserByIdentityRow, error) {
	row := q.db.QueryRow(ctx, findUserByIdentity, arg.Provider, arg.ProviderUserID)
	var i FindUserByIdentityRow
	err := row.Scan(
		&i.ID,
		&i.PrimaryEmail,
		&i.EmailVerifiedAt,
		&i.OnboardingStatus,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT
  user_id::text AS user_id,
  first_name,
  last_name,
  username::text AS username,
  phone_e164,
  phone_country_code,
  phone_national_number,
  date_of_birth,
  avatar_object_key,
  avatar_url,
  bio,
  created_at,
  updated_at
FROM user_profiles
WHERE user_id = $1::uuid
`

type GetUserProfileRow struct {
	UserID              string             `json:"user_id"`
	FirstName           string             `json:"first_name"`
	LastName            string             `json:"last_name"`
	Username            string             `json:"username"`
	PhoneE164           *string            `json:"phone_e164"`
	PhoneCountryCode    *string            `json:"phone_country_code"`
	PhoneNationalNumber *string            `json:"phone_national_number"`
	DateOfBirth         pgtype.Date        `json:"date_of_birth"`
	AvatarObjectKey     *string            `json:"avatar_object_key"`
	AvatarUrl           *string            `json:"avatar_url"`
	Bio                 *string            `json:"bio"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserProfile(ctx context.Context, userID pgtype.UUID) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, userID)
	var i GetUserProfileRow
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PhoneE164,
		&i.PhoneCountryCode,
		&i.PhoneNationalNumber,
		&i.DateOfBirth,
		&i.AvatarObjectKey,
		&i.AvatarUrl,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isUsernameTakenByAnotherUser = `-- name: IsUsernameTakenByAnotherUser :one
SELECT EXISTS (
  SELECT 1
  FROM user_profiles
  WHERE username = $1::citext
    AND user_id <> $2::uuid
) AS taken
`

type IsUsernameTakenByAnotherUserParams struct {
	Username      string      `json:"username"`
	CurrentUserID pgtype.UUID `json:"current_user_id"`
}

func (q *Queries) IsUsernameTakenByAnotherUser(ctx context.Context, arg IsUsernameTakenByAnotherUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUsernameTakenByAnotherUser, arg.Username, arg.CurrentUserID)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const updateLastLogin = `-- name: UpdateLastLogin :one
UPDATE users
SET
  last_login_at = now(),
  email_verified_at = CASE
    WHEN $1::boolean AND email_verified_at IS NULL THEN now()
    ELSE email_verified_at
  END,
  primary_email = COALESCE(primary_email, $2)
WHERE id = $3::uuid
RETURNING
  id::text AS id,
  primary_email,
  email_verified_at,
  onboarding_status::text AS onboarding_status,
  last_login_at,
  created_at,
  updated_at
`

type UpdateLastLoginParams struct {
	EmailVerified bool        `json:"email_verified"`
	PrimaryEmail  *string     `json:"primary_email"`
	UserID        pgtype.UUID `json:"user_id"`
}

type UpdateLastLoginRow struct {
	ID               string             `json:"id"`
	PrimaryEmail     *string            `json:"primary_email"`
	EmailVerifiedAt  pgtype.Timestamptz `json:"email_verified_at"`
	OnboardingStatus string             `json:"onboarding_status"`
	LastLoginAt      pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) (UpdateLastLoginRow, error) {
	row := q.db.QueryRow(ctx, updateLastLogin, arg.EmailVerified, arg.PrimaryEmail, arg.UserID)
	var i UpdateLastLoginRow
	err := row.Scan(
		&i.ID,
		&i.PrimaryEmail,
		&i.EmailVerifiedAt,
		&i.OnboardingStatus,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIdentity = `-- name: UpsertIdentity :exec
INSERT INTO user_auth_identities (
  user_id, provider, provider_user_id, email, email_verified, raw_profile, linked_at, last_used_at
)
VALUES (
  $1::uuid,
  $2::auth_provider,
  $3,
  $4,
  $5,
  $6::jsonb,
  now(),
  now()
)
ON CONFLICT (provider, provider_user_id)
DO UPDATE SET
  user_id = EXCLUDED.user_id,
  email = EXCLUDED.email,
  email_verified = EXCLUDED.email_verified,
  raw_profile = EXCLUDED.raw_profile,
  last_used_at = now()
`

type UpsertIdentityParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	Provider       interface{} `json:"provider"`
	ProviderUserID string      `json:"provider_user_id"`
	Email          *string     `json:"email"`
	EmailVerified  bool        `json:"email_verified"`
	RawProfile     []byte      `json:"raw_profile"`
}

func (q *Queries) UpsertIdentity(ctx context.Context, arg UpsertIdentityParams) error {
	_, err := q.db.Exec(ctx, upsertIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
		arg.EmailVerified,
		arg.RawProfile,
	)
	return err
}

const upsertUserProfile = `-- name: UpsertUserProfile :one
INSERT INTO user_profiles (
  user_id,
  first_name,
  last_name,
  username,
  phone_e164,
  phone_country_code,
  phone_national_number,
  date_of_birth,
  avatar_object_key,
  avatar_url,
  bio
)
VALUES (
  $1::uuid,
  $2,
  $3,
  $4::citext,
  $5,
  $6,
  $7,
  $8::date,
  $9,
  $10,
  $11
)
ON CONFLICT (user_id) DO UPDATE SET
  first_name = EXCLUDED.first_name,
  last_name = EXCLUDED.last_name,
  username = EXCLUDED.username,
  phone_e164 = EXCLUDED.phone_e164,
  phone_country_code = EXCLUDED.phone_country_code,
  phone_national_number = EXCLUDED.phone_national_number,
  date_of_birth = EXCLUDED.date_of_birth,
  avatar_object_key = EXCLUDED.avatar_object_key,
  avatar_url = EXCLUDED.avatar_url,
  bio = EXCLUDED.bio,
  updated_at = now()
RETURNING
  user_id::text AS user_id,
  first_name,
  last_name,
  username::text AS username,
  phone_e164,
  phone_country_code,
  phone_national_number,
  date_of_birth,
  avatar_object_key,
  avatar_url,
  bio,
  created_at,
  updated_at
`

type UpsertUserProfileParams struct {
	UserID              pgtype.UUID `json:"user_id"`
	FirstName           string      `json:"first_name"`
	LastName            string      `json:"last_name"`
	Username            string      `json:"username"`
	PhoneE164           *string     `json:"phone_e164"`
	PhoneCountryCode    *string     `json:"phone_country_code"`
	PhoneNationalNumber *string     `json:"phone_national_number"`
	DateOfBirth         pgtype.Date `json:"date_of_birth"`
	AvatarObjectKey     *string     `json:"avatar_object_key"`
	AvatarUrl           *string     `json:"avatar_url"`
	Bio                 *string     `json:"bio"`
}

type UpsertUserProfileRow struct {
	UserID              string             `json:"user_id"`
	FirstName           string             `json:"first_name"`
	LastName            string             `json:"last_name"`
	Username            string             `json:"username"`
	PhoneE164           *string            `json:"phone_e164"`
	PhoneCountryCode    *string            `json:"phone_country_code"`
	PhoneNationalNumber *string            `json:"phone_national_number"`
	DateOfBirth         pgtype.Date        `json:"date_of_birth"`
	AvatarObjectKey     *string            `json:"avatar_object_key"`
	AvatarUrl           *string            `json:"avatar_url"`
	Bio                 *string            `json:"bio"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UpsertUserProfileRow, error) {
	row := q.db.QueryRow(ctx, upsertUserProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.PhoneE164,
		arg.PhoneCountryCode,
		arg.PhoneNationalNumber,
		arg.DateOfBirth,
		arg.AvatarObjectKey,
		arg.AvatarUrl,
		arg.Bio,
	)
	var i UpsertUserProfileRow
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.PhoneE164,
		&i.PhoneCountryCode,
		&i.PhoneNationalNumber,
		&i.DateOfBirth,
		&i.AvatarObjectKey,
		&i.AvatarUrl,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
